### ISSUE TITLE
NullPointerException in PerChannelBookieClient

### ISSUE THREAD

**Issue by merlimat** [apache/bookkeeper#1241]
I have seen this error in `PerChannelBookieClient` with the latest master code:

```
18:36:28.989 [bookkeeper-io-5-1] WARN  io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.apache.bookkeeper.proto.PerChannelBookieClient$3.operationComplete()
java.lang.NullPointerException: null
	at org.apache.bookkeeper.proto.PerChannelBookieClient$3.operationComplete(PerChannelBookieClient.java:885) ~[org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0-20180309.150140-65.jar:4.7.0-SNAPSHOT]
	at org.apache.bookkeeper.proto.PerChannelBookieClient$3.operationComplete(PerChannelBookieClient.java:879) ~[org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0-20180309.150140-65.jar:4.7.0-SNAPSHOT]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:512) [io.netty-netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486) [io.netty-netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34) [io.netty-netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:436) [io.netty-netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [io.netty-netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [io.netty-netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) [io.netty-netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [io.netty-netty-all-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.21.Final.jar:4.1.21.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by merlimat** [comment]
I think this was added in f3166dde6f0429be121110ee534a5574d136248a

A portion of that commit: 
```diff
@@ -861,7 +875,21 @@ public class PerChannelBookieClient extends ChannelInboundHandlerAdapter {
         }

         try {
-            channel.writeAndFlush(request, channel.voidPromise());
+            final long startTime = MathUtils.nowInNano();
+            ChannelFuture future = channel.writeAndFlush(request);
+            future.addListener(new ChannelFutureListener() {
+                @Override
+                public void operationComplete(ChannelFuture future) throws Exception {
+                    if (future.isSuccess()) {
+                        nettyOpLogger.registerSuccessfulEvent(MathUtils.elapsedNanos(startTime),
+                                TimeUnit.NANOSECONDS);
+                        completionObjects.get(key).setOutstanding();
+                    } else {
+                        nettyOpLogger.registerFailedEvent(MathUtils.elapsedNanos(startTime),
+                                TimeUnit.NANOSECONDS);
+                    }
+                }
+            });
         } catch (Throwable e) {
             LOG.warn("Operation {} failed", requestToString(request), e);
             errorOut(key);
```

```java
 completionObjects.get(key).setOutstanding();
```

This should be checking the completion object is not null.

**Comment by merlimat** [comment]
Also, I don't understand well the logic here. 

I think teh `setOutstanding()` should be called *before* doing the `writeAndFlush()` and not when we did write on the channel is completed. 

The channel might not be writable (thus the future doesn't complete immediately) but from our perspective the  operation is still outstanding. 

@kishorekasi Can you confirm?

**Comment by kishorekasi** [comment]
"but from our perspective the operation is still outstanding." - That is one way to see it. My perspective was different; Netty is used as a library, so it is part of the client. If a request is buffered in Netty, then I counted is not being outstanding. Only when the request made it to the wire, I counted it outstanding.

**Comment by kishorekasi** [comment]
Are there cases where completionObject is null will outstanding requests?

**Comment by merlimat** [comment]
> Are there cases where completionObject is null will outstanding requests? 

Not exactly sure why, but I got the exception, so definitely can happen :)
