### ISSUE TITLE
ArrayIndexOutOfBoundsException is thrown on readLastAddConfirmedAndEntry

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1403]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

write an integration test on testing long poll reads

- What did you expect to see?

integration test can pass

- What did you see instead?

the integration test hangs on.

```
2018-05-12 03:41:11,910 - ERROR - [BookKeeperClientWorker-OrderedExecutor-0-0:SafeRunnable@38] - Unexpected throwable caught
java.lang.ArrayIndexOutOfBoundsException: 2
	at org.apache.bookkeeper.client.RoundRobinDistributionSchedule$WriteSetImpl.get(RoundRobinDistributionSchedule.java:123)
	at org.apache.bookkeeper.client.ReadLastConfirmedAndEntryOp$SequenceReadRequest.sendNextRead(ReadLastConfirmedAndEntryOp.java:373)
	at org.apache.bookkeeper.client.ReadLastConfirmedAndEntryOp$SequenceReadRequest.logErrorAndReattemptRead(ReadLastConfirmedAndEntryOp.java:406)
	at org.apache.bookkeeper.client.ReadLastConfirmedAndEntryOp.readEntryComplete(ReadLastConfirmedAndEntryOp.java:602)
	at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion$1.readEntryComplete(PerChannelBookieClient.java:1633)
	at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion.handleReadResponse(PerChannelBookieClient.java:1714)
	at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion.handleV3Response(PerChannelBookieClient.java:1689)
	at org.apache.bookkeeper.proto.PerChannelBookieClient$3.safeRun(PerChannelBookieClient.java:1304)
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sijie** [comment]
This bug is a regression from #657.
