### ISSUE TITLE
[DbLedgerStorage] IllegalReferenceCount on filling readahead cache

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1487]
*Problem*

Running pulsar standalone with bookkeeper master. 

```
02:45:55.430 [BookieReadThreadPool-OrderedExecutor-3-0] DEBUG org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage - Ledger exists. ledger: 19 : true
02:45:55.431 [BookieReadThreadPool-OrderedExecutor-3-0] DEBUG org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage - Get Entry: 19@0
02:45:55.431 [BookieReadThreadPool-OrderedExecutor-3-0] DEBUG org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage - Exception during read ahead for ledger: 19: e
io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100) ~[netty-all-4.1.22.Final.jar:4.1.22.Final]
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84) ~[netty-all-4.1.22.Final.jar:4.1.22.Final]
        at org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage.fillReadAheadCache(SingleDirectoryDbLedgerStorage.java:537) [bookkeeper-server-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage.getEntry(SingleDirectoryDbLedgerStorage.java:500) [bookkeeper-server-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage.getEntry(DbLedgerStorage.java:222) [bookkeeper-server-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.apache.bookkeeper.bookie.LedgerDescriptorImpl.readEntry(LedgerDescriptorImpl.java:153) [bookkeeper-server-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.apache.bookkeeper.bookie.Bookie.readEntry(Bookie.java:1302) [bookkeeper-server-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.apache.bookkeeper.proto.ReadEntryProcessorV3.readEntry(ReadEntryProcessorV3.java:177) [bookkeeper-server-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.apache.bookkeeper.proto.ReadEntryProcessorV3.readEntry(ReadEntryProcessorV3.java:157) [bookkeeper-server-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.apache.bookkeeper.proto.ReadEntryProcessorV3.getReadResponse(ReadEntryProcessorV3.java:220) [bookkeeper-server-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.apache.bookkeeper.proto.ReadEntryProcessorV3.executeOp(ReadEntryProcessorV3.java:263) [bookkeeper-server-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.apache.bookkeeper.proto.ReadEntryProcessorV3.safeRun(ReadEntryProcessorV3.java:259) [bookkeeper-server-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [bookkeeper-common-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.22.Final.jar:4.1.22.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by sijie** [comment]
This is fixed at #1488
