### ISSUE TITLE
logging "No network topology script is found when using script based DNS resolver" can be noisy and misleading.

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1528]
```
java.lang.RuntimeException: No network topology script is found when using script based DNS resolver.
    at org.apache.bookkeeper.net.ScriptBasedMapping$RawScriptBasedMapping.setConf(ScriptBasedMapping.java:150) ~[org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0.jar:4.7.0]
    at org.apache.bookkeeper.net.ScriptBasedMapping.setConf(ScriptBasedMapping.java:122) ~[org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0.jar:4.7.0]
    at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.initialize(RackawareEnsemblePlacementPolicyImpl.java:306) [org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0.jar:4.7.0]
    at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.initialize(RackawareEnsemblePlacementPolicyImpl.java:75) [org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0.jar:4.7.0]
    at org.apache.bookkeeper.client.BookKeeper.initializeEnsemblePlacementPolicy(BookKeeper.java:598) [org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0.jar:4.7.0]
    at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:490) [org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0.jar:4.7.0]
    at org.apache.bookkeeper.client.BookKeeper$Builder.build(BookKeeper.java:308) [org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0.jar:4.7.0]
    at org.apache.bookkeeper.replication.ReplicationWorker.<init>(ReplicationWorker.java:131) [org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0.jar:4.7.0]
    at org.apache.bookkeeper.replication.AutoRecoveryMain.<init>(AutoRecoveryMain.java:111) [org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0.jar:4.7.0]
    at org.apache.bookkeeper.replication.AutoRecoveryMain.<init>(AutoRecoveryMain.java:81) [org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0.jar:4.7.0]
    at org.apache.bookkeeper.replication.AutoRecoveryMain.main(AutoRecoveryMain.java:303) [org.apache.bookkeeper-bookkeeper-server-shaded-4.7.0.jar:4.7.0]
```

**Comment by eolivelli** [comment]
I agree
