### ISSUE TITLE
Unable to run 'bookkeeper' shell script from /bookkeeper/bin folder

### ISSUE THREAD

**Issue by reddycharan** [apache/bookkeeper#1542]
**BUG REPORT**

Getting NoClassDefFoundError while trying to run 'bookkeeper' shell script from 'bin' folder. Issue seems to be related with classpath (cached classpath file - cached_classpath.txt)

~/Workspace/Community/bookkeeper/bin$ ./bookkeeper shell
JAVA_HOME not set, using java from PATH. (/usr/bin/java)
cat: bookkeeper-server/target/cached_classpath.txt: No such file or directory
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/configuration/Configuration
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.configuration.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

But If I run 'bookkeeper' shell script from parent directory then it is working fine

~/Workspace/Community/bookkeeper$ ./bin/bookkeeper shell
JAVA_HOME not set, using java from PATH. (/usr/bin/java)
Usage: bookkeeper shell [-localbookie [<host:port>]] [-ledgeridformat <hex/long/uuid>] [-entryformat <hex/string>] [-conf configuration] <command>
where command is one of:
...

**Comment by reddycharan** [comment]
@sijie it might be related to your changes on bookkeeper/bin/common.sh
