### ISSUE TITLE
MdcContextTest fails on testAddFailsWithReadOnlyBookie

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1696]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

build and test build

- What did you expect to see?

all the unit tests passed

- What did you see instead?

```
[ERROR] testAddFailsWithReadOnlyBookie(org.apache.bookkeeper.client.MdcContextTest)  Time elapsed: 3.92 s  <<< ERROR!
java.util.ConcurrentModificationException
	at org.apache.bookkeeper.client.MdcContextTest.assertLogWithMdc(MdcContextTest.java:97)
	at org.apache.bookkeeper.client.MdcContextTest.testAddFailsWithReadOnlyBookie(MdcContextTest.java:195)
```

**Comment by sijie** [comment]
@dlg99 I saw a test related to MdcContextTest was failing on my laptop. wondering if you have any cycles to look into this test?

**Comment by eolivelli** [comment]
Do we have an old version of the library? I saw that kind of errors in the past on other projects with MDC but in those case there were old versions of the lib

**Comment by dlg99** [comment]
@eolivelli stack points to the mock / List used in the mock.
@sijie I cannot repro this locally, ran the test suite in the loop for a long time.

my guess the following patch should help but I cannot repro the failure even without it.
Can you give it a try?

```
diff --git a/bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MdcContextTest.java b/bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MdcContextTest.java
index f10427b8b..535b97a4b 100644
--- a/bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MdcContextTest.java
+++ b/bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MdcContextTest.java
@@ -32,8 +32,8 @@ import static org.mockito.Mockito.mock;
 import static org.mockito.Mockito.when;

 import java.io.File;
-import java.util.LinkedList;
-import java.util.List;
+import java.util.Queue;
+import java.util.concurrent.ConcurrentLinkedQueue;

 import lombok.extern.slf4j.Slf4j;

@@ -69,7 +69,7 @@ public class MdcContextTest extends BookKeeperClusterTestCase {
     LedgerHandle lh;

     private Appender mockAppender;
-    private List<String> capturedEvents;
+    private Queue<String> capturedEvents;
     private Logger rootLogger = LogManager.getRootLogger();

     public MdcContextTest() {
@@ -122,7 +122,7 @@ public class MdcContextTest extends BookKeeperClusterTestCase {

         rootLogger.addAppender(mockAppender);
         rootLogger.setLevel(Level.INFO);
-        capturedEvents = new LinkedList<>();
+        capturedEvents = new ConcurrentLinkedQueue<>();

         doAnswer(answerVoid((LoggingEvent event) -> capturedEvents.add(
                     mdcFormat(event.getMDC(MDC_REQUEST_ID), event.getRenderedMessage())
```

**Comment by eolivelli** [comment]
@dlg99 you are right.
The patch makes sense. Please send a PR

**Comment by eolivelli** [comment]
On current master:
```
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.157 s <<< FAILURE! - in org.apache.bookkeeper.client.MdcContextTest
[ERROR] testSimpleAdd(org.apache.bookkeeper.client.MdcContextTest)  Time elapsed: 2.42 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: a collection containing (a string containing "[request_id:ledger_add_entry] - " and a string containing "Successfully connected to bookie")
     but: a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Authentication success on server side", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Successfully connected to bookie: [id: 0xd8dc708d, L:/127.0.0.1:49620 - R:localhost/127.0.0.1:37809]", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Successfully connected to bookie: [id: 0x8da9ce29, L:/127.0.0.1:41596 - R:localhost/127.0.0.1:33441]", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Successfully connected to bookie: 127.0.0.1:33441", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Successfully connected to bookie: [id: 0xbd4319f9, L:/127.0.0.1:60234 - R:localhost/127.0.0.1:33711]", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Successfully connected to bookie: 127.0.0.1:33711", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Authentication success on server side", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Authentication success on server side", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Channel connected  [id: 0xbcbb066c, L:/127.0.0.1:33711 - R:/127.0.0.1:60234]", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Channel connected  [id: 0x3828814d, L:/127.0.0.1:37809 - R:/127.0.0.1:49620]", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Successfully connected to bookie: 127.0.0.1:37809", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Channel connected  [id: 0x7f78d57b, L:/127.0.0.1:33441 - R:/127.0.0.1:41596]", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - connection [id: 0x8da9ce29, L:/127.0.0.1:41596 - R:localhost/127.0.0.1:33441] authenticated as BookKeeperPrincipal{ANONYMOUS}", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - connection [id: 0xbd4319f9, L:/127.0.0.1:60234 - R:localhost/127.0.0.1:33711] authenticated as BookKeeperPrincipal{ANONYMOUS}", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - connection [id: 0xd8dc708d, L:/127.0.0.1:49620 - R:localhost/127.0.0.1:37809] authenticated as BookKeeperPrincipal{ANONYMOUS}", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Created new entry log file /tmp/bookie6185318353567409418test/current/0.log for logId 0.", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Created new entry log file /tmp/bookie15839036013516068130test/current/0.log for logId 0.", a string containing "[request_id:ledger_add_entry] - " was "[request_id:] - Created new entry log file /tmp/bookie8514984730301709604test/current/0.log for logId 0."
	at org.apache.bookkeeper.client.MdcContextTest.assertLogWithMdc(MdcContextTest.java:97)
	at org.apache.bookkeeper.client.MdcContextTest.testSimpleAdd(MdcContextTest.java:160)

```
