### ISSUE TITLE
IllegalReferenceCountException at closing EntryLogManagerForSingleEntryLog

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1703]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

run bookkeeper standalone

- What did you expect to see?

bookkeeper runs well and no surprise in the log

- What did you see instead?

```
2018-09-24 19:03:58,116 - WARN  [component-shutdown-thread:Slf4JLogger@146] - Failed to release a message: PooledUnsafeDirectByteBuf(freed)
io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
        at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
        at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113)
        at org.apache.bookkeeper.bookie.BufferedChannel.close(BufferedChannel.java:91)
        at org.apache.bookkeeper.util.IOUtils.close(IOUtils.java:48)
        at org.apache.bookkeeper.bookie.EntryLogManagerForSingleEntryLog.forceClose(EntryLogManagerForSingleEntryLog.java:221)
        at org.apache.bookkeeper.bookie.EntryLogger.shutdown(EntryLogger.java:1087)
        at org.apache.bookkeeper.bookie.InterleavedLedgerStorage.shutdown(InterleavedLedgerStorage.java:186)
        at org.apache.bookkeeper.bookie.SortedLedgerStorage.shutdown(SortedLedgerStorage.java:124)
        at org.apache.bookkeeper.bookie.Bookie.shutdown(Bookie.java:1099)
        at org.apache.bookkeeper.bookie.Bookie.shutdown(Bookie.java:1068)
        at org.apache.bookkeeper.proto.BookieServer.shutdown(BookieServer.java:201)
        at org.apache.bookkeeper.server.service.BookieService.doClose(BookieService.java:71)
        at org.apache.bookkeeper.common.component.AbstractLifecycleComponent.close(AbstractLifecycleComponent.java:109)
        at org.apache.bookkeeper.common.component.LifecycleComponentStack.lambda$close$4(LifecycleComponentStack.java:123)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
        at org.apache.bookkeeper.common.component.LifecycleComponentStack.close(LifecycleComponentStack.java:123)
        at org.apache.bookkeeper.common.component.ComponentStarter$ComponentShutdownHook.run(ComponentStarter.java:46)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by eolivelli** [comment]
This can lead to a double release, no?
Double release = possible data corruption ?

**Comment by sijie** [comment]
@eolivelli this happens at closing as what I put in the caption. so I don't think it impacts anything.

**Comment by sijie** [comment]
We are seeing this pretty often in pulsar when I attempted to use the latest master in pulsar.

https://builds.apache.org/job/pulsar_precommit_java8/4180/testReport/junit/org.apache.bookkeeper.mledger.impl/ManagedLedgerBkTest/ledgerFencedByAutoReplication/

```
01:23:25.886 [main:io.netty.util.internal.logging.Slf4JLogger@146] WARN  io.netty.util.ReferenceCountUtil - Failed to release a message: PooledUnsafeDirectByteBuf(freed)
io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100) ~[netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84) ~[netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88) ~[netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at org.apache.bookkeeper.bookie.BufferedChannel.close(BufferedChannel.java:91) [bookkeeper-server-4.9.0-20181003-897c643-SNAPSHOT.jar:4.9.0-20181003-897c643-SNAPSHOT]
	at org.apache.bookkeeper.util.IOUtils.close(IOUtils.java:48) [bookkeeper-server-4.9.0-20181003-897c643-SNAPSHOT.jar:4.9.0-20181003-897c643-SNAPSHOT]
	at org.apache.bookkeeper.bookie.EntryLogManagerForSingleEntryLog.forceClose(EntryLogManagerForSingleEntryLog.java:221) [bookkeeper-server-4.9.0-20181003-897c643-SNAPSHOT.jar:4.9.0-20181003-897c643-SNAPSHOT]
	at org.apache.bookkeeper.bookie.EntryLogger.shutdown(EntryLogger.java:1087) [bookkeeper-server-4.9.0-20181003-897c643-SNAPSHOT.jar:4.9.0-20181003-897c643-SNAPSHOT]
	at org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage.shutdown(SingleDirectoryDbLedgerStorage.java:272) [bookkeeper-server-4.9.0-20181003-897c643-SNAPSHOT.jar:4.9.0-20181003-897c643-SNAPSHOT]
	at org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage.shutdown(DbLedgerStorage.java:185) [bookkeeper-server-4.9.0-20181003-897c643-SNAPSHOT.jar:4.9.0-20181003-897c643-SNAPSHOT]
	at org.apache.bookkeeper.bookie.Bookie.shutdown(Bookie.java:1099) [bookkeeper-server-4.9.0-20181003-897c643-SNAPSHOT.jar:4.9.0-20181003-897c643-SNAPSHOT]
	at org.apache.bookkeeper.bookie.Bookie.shutdown(Bookie.java:1068) [bookkeeper-server-4.9.0-20181003-897c643-SNAPSHOT.jar:4.9.0-20181003-897c643-SNAPSHOT]
	at org.apache.bookkeeper.proto.BookieServer.shutdown(BookieServer.java:201) [bookkeeper-server-4.9.0-20181003-897c643-SNAPSHOT.jar:4.9.0-20181003-897c643-SNAPSHOT]
	at org.apache.bookkeeper.test.BookKeeperClusterTestCase.stopBKCluster(BookKeeperClusterTestCase.java:169) [test-classes/:?]
	at org.apache.bookkeeper.test.BookKeeperClusterTestCase.tearDown(BookKeeperClusterTestCase.java:113) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
```
