### ISSUE TITLE
OutOfDirectMemoryError with isForceGCAllowWhenNoSpace=true

### ISSUE THREAD

**Issue by hamadodene** [apache/bookkeeper#1783]
I inserted "bookie.advanced.isForceGCAllowWhenNoSpace=true"
in the bookkeeper service.conf to free up some space,
but it returned OutOfMemoryError to me. 
I solved by adding the flag "-XX:MaxDirectMemorySize=2G" in the 
configuration files and restarting the server.

18-11-05-17-17-33       Unexpected throwable caught
18-11-05-17-17-33       io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 1113083513 byte(s) of direct memory (used: 67108864, max: 805306368)
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 1113083513 byte(s) of direct memory (used: 67108864, max: 805306368)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
        at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:754)
        at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:260)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:231)
        at io.netty.buffer.PoolArena.reallocate(PoolArena.java:397)
        at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118)
        at org.apache.bookkeeper.bookie.EntryLogger.scanEntryLog(EntryLogger.java:1219)
        at org.apache.bookkeeper.bookie.EntryLogger.extractEntryLogMetadataByScanning(EntryLogger.java:1337)
        at org.apache.bookkeeper.bookie.EntryLogger.getEntryLogMetadata(EntryLogger.java:1246)
        at org.apache.bookkeeper.bookie.GarbageCollectorThread.extractMetaFromEntryLogs(GarbageCollectorThread.java:564)
        at org.apache.bookkeeper.bookie.GarbageCollectorThread.runWithFlags(GarbageCollectorThread.java:352)
        at org.apache.bookkeeper.bookie.GarbageCollectorThread.safeRun(GarbageCollectorThread.java:333)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by eolivelli** [comment]
Side note: bookie.advanced.xxx is the way to pass configuration parameters to the Bookie in MagNews platform.

It seems that the bookie is allocating in memory the whole new file to be written.

@hamadodene can you please write about your case? The size of the files with data  and why you tried to add such flag?

**Comment by sijie** [comment]
It seems it is a setting problem. Close it for now. If there is anything required from bookkeeper, please reopen it.
