### ISSUE TITLE
Cannot run Bookie with JDK8 if build on JDK-11

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#1913]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?
I have built BK 4.9 with jdk-11 and launched "localbookie"

- What did you expect to see?
The bookie is running

- What did you see instead?

```
2019-01-22 16:43:16,519 - ERROR - [BookieJournal-5000:BookieCriticalThread@41] - Uncaught exception in thread BookieJournal-5000 and is exiting!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.apache.bookkeeper.bookie.JournalChannel.<init>(JournalChannel.java:169)
	at org.apache.bookkeeper.bookie.JournalChannel.<init>(JournalChannel.java:114)
	at org.apache.bookkeeper.bookie.Journal.run(Journal.java:976)

```

**Comment by eolivelli** [comment]
This is actually a non-issue because we are releasing convenience binaries built on docker with jdk8.
This problem may arise in the future.

It is due to the new ByteBuffer#clear() covariant method which returns a ByteBuffer and not a Buffer as in JDK8. The problem is there since JDK9.

I have created this issue in order to track the problem, not willing to fix it.
The best fix would be to pass  "release=8" argument to the javac compiler but this works only from jdk9+ 
Another fix is to cast explicitly the ByteBuffer variable to "Buffer" so that javac generates the "compatbile" bytecode
