### ISSUE TITLE
bkctl simpletest fails silently

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#1922]
if bkctl simpletest fails, it exits without output. This is confusing for the user.

```
ivan@tethra:~/Junk/bookkeeper-4.9.0-rc1/bkctl-4.9.0$ bin/bkctl ledger simpletest
JAVA_HOME not set, using java from PATH. (/usr/bin/java)
ivan@tethra:~/Junk/bookkeeper-4.9.0-rc1/bkctl-4.9.0$ echo $?
255
```
In this case it was failing because there weren't enough bookies.

**Comment by Ghatage** [comment]
@ivankelly I ran bkctl simpletest with nothing setup and it failed with printing the stack traces.. do you think we can close this now?

```
 ~/community> ./bin/bkctl ledger simpletest               
JAVA_HOME not set, using java from PATH. (/usr/bin/java)
the classpath of module 'tools/all' is not found, generating it ...
see output at /Users/aghatage/community/tools/all/target/build_classpath.out for the progress ...
the classpath of module 'tools/all' is generated at '/Users/aghatage/community/tools/all/target/cached_classpath.txt'.
11:38:14,290 ERROR Failed to create zookeeper client to localhost:2181
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.waitForConnection(ZooKeeperWatcherBase.java:159)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$Builder.build(ZooKeeperClient.java:257)
	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:197)
	at org.apache.bookkeeper.meta.zk.ZKMetadataClientDriver.initialize(ZKMetadataClientDriver.java:62)
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:445)
	at org.apache.bookkeeper.client.BookKeeper$Builder.build(BookKeeper.java:298)
	at org.apache.bookkeeper.client.impl.BookKeeperBuilderImpl.build(BookKeeperBuilderImpl.java:86)
	at org.apache.bookkeeper.tools.cli.helpers.ClientCommand.apply(ClientCommand.java:65)
	at org.apache.bookkeeper.tools.cli.helpers.ClientCommand.apply(ClientCommand.java:54)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:94)
	at org.apache.bookkeeper.tools.common.BKCommand.lambda$apply$0(BKCommand.java:49)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:224)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:51)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:39)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:232)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.framework.CliCommandGroup.apply(CliCommandGroup.java:68)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:232)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.cli.BKCtl.main(BKCtl.java:58)
11:38:14,292 ERROR Encountered metadata exceptions on initializing metadata client driver
org.apache.bookkeeper.meta.exceptions.MetadataException: Failed to create zookeeper client to localhost:2181
	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:217)
	at org.apache.bookkeeper.meta.zk.ZKMetadataClientDriver.initialize(ZKMetadataClientDriver.java:62)
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:445)
	at org.apache.bookkeeper.client.BookKeeper$Builder.build(BookKeeper.java:298)
	at org.apache.bookkeeper.client.impl.BookKeeperBuilderImpl.build(BookKeeperBuilderImpl.java:86)
	at org.apache.bookkeeper.tools.cli.helpers.ClientCommand.apply(ClientCommand.java:65)
	at org.apache.bookkeeper.tools.cli.helpers.ClientCommand.apply(ClientCommand.java:54)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:94)
	at org.apache.bookkeeper.tools.common.BKCommand.lambda$apply$0(BKCommand.java:49)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:224)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:51)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:39)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:232)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.framework.CliCommandGroup.apply(CliCommandGroup.java:68)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:232)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.cli.BKCtl.main(BKCtl.java:58)
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.waitForConnection(ZooKeeperWatcherBase.java:159)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$Builder.build(ZooKeeperClient.java:257)
	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:197)
	... 18 more
11:38:14,293 ERROR Failed to process command 'simpletest'
java.io.IOException: Failed to initialize metadata client driver
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:455)
	at org.apache.bookkeeper.client.BookKeeper$Builder.build(BookKeeper.java:298)
	at org.apache.bookkeeper.client.impl.BookKeeperBuilderImpl.build(BookKeeperBuilderImpl.java:86)
	at org.apache.bookkeeper.tools.cli.helpers.ClientCommand.apply(ClientCommand.java:65)
	at org.apache.bookkeeper.tools.cli.helpers.ClientCommand.apply(ClientCommand.java:54)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:94)
	at org.apache.bookkeeper.tools.common.BKCommand.lambda$apply$0(BKCommand.java:49)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:224)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:51)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:39)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:232)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.framework.CliCommandGroup.apply(CliCommandGroup.java:68)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:232)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.cli.BKCtl.main(BKCtl.java:58)
Caused by: org.apache.bookkeeper.meta.exceptions.MetadataException: Failed to create zookeeper client to localhost:2181
	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:217)
	at org.apache.bookkeeper.meta.zk.ZKMetadataClientDriver.initialize(ZKMetadataClientDriver.java:62)
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:445)
	... 16 more
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.waitForConnection(ZooKeeperWatcherBase.java:159)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$Builder.build(ZooKeeperClient.java:257)
	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:197)
	... 18 more
 ~/community> echo $?                                                                                                                                                                                     
255
```
