### ISSUE TITLE
localbookie error messages are rubbish when started incorrectly

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#1925]
I couldn't remember the correct invokation. It didn't help me.

```
ivan@tethra:~/Junk/bookkeeper-4.9.0-rc1/bookkeeper-all-4.9.0$ bin/bookkeeper localbookie
JAVA_HOME not set, using java from PATH. (/usr/bin/java)
ivan@tethra:~/Junk/bookkeeper-4.9.0-rc1/bookkeeper-all-4.9.0$ bin/bookkeeper localbookie -n 5
JAVA_HOME not set, using java from PATH. (/usr/bin/java)
2019-01-31 11:44:44,618 - ERROR - [main:LocalBookKeeper@477] - Exiting LocalBookKeeper because of exception in main method
java.lang.NumberFormatException: For input string: "-n"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.apache.bookkeeper.util.LocalBookKeeper.main(LocalBookKeeper.java:449)
java.lang.NumberFormatException: For input string: "-n"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.apache.bookkeeper.util.LocalBookKeeper.main(LocalBookKeeper.java:449)
```

**Comment by zymap** [comment]
Just input `bin/bookkeeper localbookie n`, it works well.

**Comment by ivankelly** [comment]
@zymap yes, that's not what this issue is about. This issue is that if you don't get the invocation correct, the error messages are completely unhelpful
