### ISSUE TITLE
MethodNotFoundException due to old Guava version.

### ISSUE THREAD

**Issue by artus** [apache/bookkeeper#1936]
This is a bug report

**BUG REPORT**

1. Please describe the issue you observed:

- We use the distributedlog-common library 4.3.7, which has a dependency on Guava 21.0
- We also use Guava 27.0.1 in our project ourselves (which has the distributedlog-common library as a dependency)
- We try writing to a log in distributedlog.

- We expect the record to be written.

- An exception is thrown:

> java.lang.NoSuchMethodError: com.google.common.util.concurrent.Futures.addCallback(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/util/concurrent/FutureCallback;)V
	at org.apache.distributedlog.BKLogSegmentWriter.addComplete(BKLogSegmentWriter.java:1214) ~[distributedlog-core-4.7.3.jar:4.7.3]
	at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:91) ~[bookkeeper-server-4.7.3.jar:4.7.3]
	at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:361) ~[bookkeeper-server-4.7.3.jar:4.7.3]
	at org.apache.bookkeeper.client.LedgerHandle.sendAddSuccessCallbacks(LedgerHandle.java:1576) ~[bookkeeper-server-4.7.3.jar:4.7.3]
	at org.apache.bookkeeper.client.PendingAddOp.sendAddSuccessCallbacks(PendingAddOp.java:345) ~[bookkeeper-server-4.7.3.jar:4.7.3]
	at org.apache.bookkeeper.client.PendingAddOp.writeComplete(PendingAddOp.java:340) ~[bookkeeper-server-4.7.3.jar:4.7.3]
	at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.writeComplete(PerChannelBookieClient.java:1787) ~[bookkeeper-server-4.7.3.jar:4.7.3]
	at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.handleResponse(PerChannelBookieClient.java:1844) ~[bookkeeper-server-4.7.3.jar:4.7.3]
	at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.handleV3Response(PerChannelBookieClient.java:1833) ~[bookkeeper-server-4.7.3.jar:4.7.3]
	at org.apache.bookkeeper.proto.PerChannelBookieClient$3.safeRun(PerChannelBookieClient.java:1229) ~[bookkeeper-server-4.7.3.jar:4.7.3]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) ~[bookkeeper-common-4.7.3.jar:4.7.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by artus** [comment]
We fixed the issue by downgrading to Guava 21.0 ourselves, but this is not really acceptable as this version is almost 2 years older than the current one.

**Comment by sijie** [comment]
@artus have you tried to use `distributedlog-core-shaded` artifact instead of `distributedlog-core`. `distributedlog-core-shaded` shades the dependencies.

we will try to bump guava version in next release.

**Comment by artus** [comment]
@sijie We did not do it yet. The issue is currently fixed by just downgrading and we have other priorities now. I will try out the shaded artifact when we run into this issue again.

**Comment by shoothzj** [comment]
We have updated to guava 32.x, You can try with latest version.
