### ISSUE TITLE
Modifying configuration `nettyMaxFrameSizeBytes` does not work

### ISSUE THREAD

**Issue by hellozepp** [apache/bookkeeper#2079]
**BUG REPORT**
configuration `nettyMaxFrameSizeBytes` does not work 
***Describe the bug***
I tried to modify the configuration of bk_server to nettyMaxFrameSizeBytes=52428800(50M).I modified the bookie server-side configuration file conf/bk_server.conf, and then restart the bookkeeper service, Sending 5M data addEntry can be successful, but the following exception occurred when readEntries:
```
2019-04-29 15:10:37,498 - ERROR - [bookie-io-1-2:BookieRequestHandler@70] - Unhandled exception occurred in I/O thread or handler
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
test source code:
```
        long ledgerId = ledger.getId();
        log.info("Writing to ledger: {}", ledgerId);
        ledger.addEntry("foo".getBytes());
        ledger.addEntry(new byte[5 * 1024 * 1024 + 1]);

        ledger.close();

        LedgerHandle lh2 = bkc.openLedger(ledgerId, DigestType.CRC32, "foobar".getBytes());
        long lastEntry = lh2.getLastAddConfirmed();
        System.out.println("lastEntry:" + lastEntry);
        Enumeration<LedgerEntry> entries = lh2.readEntries(0, lastEntry);
```
Then try to modify to less than 5M to get the information.

**Comment by sijie** [comment]
@hellozepp thank you for reporting this. we will take  a look.

**Comment by zymap** [comment]
@hellozepp Do you have more error message when you use bookKeeper? Which type are you start ? I try it on my laptop it work looks good. I set `nettyMaxFrameSizeBytes=10485760` and my test code : 
```
long id = write.getId();
        long start = write.getLastAddConfirmed();
        System.out.println("start is : " + start);
        write.addEntry("hello".getBytes());
        write.addEntry(new byte[5 * 1024 * 1024]);
        write.addEntry("helloagain".getBytes());
        write.close();

        LedgerHandle read = bookKeeper.openLedger(id, BookKeeper.DigestType.MAC, pass);
        long last = read.getLastAddConfirmed();
        System.out.println("last add confirm : " + last);

        Enumeration<LedgerEntry> e = read.readEntries(0, last);
        while (e.hasMoreElements()) {
            LedgerEntry entry = e.nextElement();
            byte[] bytes = entry.getEntry();
            System.out.println(new String(bytes, StandardCharsets.UTF_8));
        }
```

**Comment by zymap** [comment]
@hellozepp  Did you add `conf.setNettyMaxFrameSizeBytes(10 * 1024 * 1024);`  on client side ?

**Comment by hellozepp** [comment]
@zymap Thanks a lot. Setting this parameter it works. Seem to the document does not indicate that this value needs to be set on the client side.

**Comment by hellozepp** [comment]
@zymap shall we prompt the user in `Description`?
over here:
http://bookkeeper.apache.org/docs/4.8.0/reference/config/#nettyMaxFrameSizeBytes

**Comment by sijie** [comment]
yes we should. @hellozepp are you interested in contributing an improvement?

**Comment by hellozepp** [comment]
yes,let me try to submit this pr @sijie

**Comment by hellozepp** [comment]
Which version of site should be modified :) @sijie

**Comment by sijie** [comment]
@hellozepp I think you can update latest first and then propagate the change to 4.9.* and 4.8.* versions.
