### ISSUE TITLE
Ledger directory is 100% used

### ISSUE THREAD

**Issue by codelipenghui** [apache/bookkeeper#2103]
**Describe the bug**
A single ledger directory is 100% used, but other directories are used very low

**Screenshots**
![image](https://user-images.githubusercontent.com/12592133/58229119-674f5f00-7d63-11e9-8710-f97142fd7748.png)

**Heap dump**
https://drive.google.com/open?id=11J9OQjCj-pYgJxu0MLzEWg8ge63H71Te

**Bookkeeper version**
4.7.2

**Comment by hrsakai** [comment]
Similar issue has happened in our environment.


Compaction suddenly stoped with following exception.
```
09:23:42.310 [GarbageCollectorThread-11-1] INFO  o.a.b.bookie.GarbageCollectorThread  - Enter minor compaction, suspendMinor false
09:23:42.310 [GarbageCollectorThread-11-1] INFO  o.a.b.bookie.GarbageCollectorThread  - Do compaction to compact those files lower than 0.2
.
.
09:25:17.681 [GarbageCollectorThread-11-1] INFO  o.a.b.bookie.EntryLogCompactor       - Removing entry log 27135 after compaction
09:25:17.810 [GarbageCollectorThread-11-1] INFO  o.a.b.bookie.GarbageCollectorThread  - Removing entry log metadata for 27135
09:25:17.810 [GarbageCollectorThread-11-1] DEBUG o.a.b.bookie.GarbageCollectorThread  - Compacting entry log 6743 below threshold 0.2
09:25:17.984 [GarbageCollectorThread-11-1] ERROR o.a.b.common.util.SafeRunnable       - Unexpected throwable caught
java.lang.IllegalArgumentException: Keys and values must be >= 0
        at org.apache.bookkeeper.util.collections.ConcurrentLongLongHashMap.checkBiggerEqualZero(ConcurrentLongLongHashMap.java:731)
        at org.apache.bookkeeper.util.collections.ConcurrentLongLongHashMap.get(ConcurrentLongLongHashMap.java:141)
        at org.apache.bookkeeper.util.collections.ConcurrentLongLongHashMap.containsKey(ConcurrentLongLongHashMap.java:147)
        at org.apache.bookkeeper.bookie.EntryLogMetadata.containsLedger(EntryLogMetadata.java:51)
        at org.apache.bookkeeper.bookie.EntryLogCompactor$CompactionScannerFactory$1.accept(EntryLogCompactor.java:85)
        at org.apache.bookkeeper.bookie.EntryLogger.scanEntryLog(EntryLogger.java:1211)
        at org.apache.bookkeeper.bookie.EntryLogCompactor.compact(EntryLogCompactor.java:56)
        at org.apache.bookkeeper.bookie.GarbageCollectorThread.compactEntryLog(GarbageCollectorThread.java:536)
        at org.apache.bookkeeper.bookie.GarbageCollectorThread.doCompactEntryLogs(GarbageCollectorThread.java:475)
        at org.apache.bookkeeper.bookie.GarbageCollectorThread.runWithFlags(GarbageCollectorThread.java:381)
        at org.apache.bookkeeper.bookie.GarbageCollectorThread.safeRun(GarbageCollectorThread.java:333)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
09:25:38.374 [bookie-io-1-53] INFO  o.a.bookkeeper.proto.AuthHandler     - Authentication success on server side
09:25:38.374 [bookie-io-1-53] INFO  o.a.b.proto.BookieRequestHandler     - Channel connected  [id: 0x614a946d, L:/xxxxxx:3181 - R:/xxxxxx:39748]
```
At this time, it seems that the `compacting` flag does not be changed to` false` because following line is not executed.
https://github.com/apache/bookkeeper/blob/release-4.7.3/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java#L538

Therefore, after this compaction, entry log files are not deleted by any other compaction until restarting the bookie.
https://github.com/apache/bookkeeper/blob/release-4.7.3/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java#L530-L534

The specific entry log id(`6743`) raises above exception on every first compaction.


There are log usage buckets logs outputted by compactions after this compaction.
(This compaction has not been reported)
```
10:58:48.317 [GarbageCollectorThread-11-1] INFO  o.a.b.bookie.GarbageCollectorThread  - Compaction: entry log usage buckets[10% 20% 30% 40% 50% 60% 70% 80% 90% 100%] = [0, 13425, 721, 320, 195, 99, 46, 18, 10, 4]
11:58:48.392 [GarbageCollectorThread-11-1] INFO  o.a.b.bookie.GarbageCollectorThread  - Compaction: entry log usage buckets[10% 20% 30% 40% 50% 60% 70% 80% 90% 100%] = [0, 13439, 716, 318, 197, 101, 45, 18, 8, 4]
```


**Bookkeeper version**
4.7.3

**settings**
```
minorCompactionThreshold=0.2
minorCompactionInterval=3600
majorCompactionThreshold=0.5
majorCompactionInterval=86400
```

**Comment by hrsakai** [comment]
I have found a negative number ledger id in entry log file.
```
$ sudo bookkeeper shell readlog 6743 |grep Lid |awk '{print $2}'|sort -rn |uniq -c
      1 Lid=-1907126707656498384,
      1 Lid=10336653,
      1 Lid=10336642,
      1 Lid=10336640,
     10 Lid=10336639,
.
.


// I can see msg by `readlog` command.
$ sudo bookkeeper shell readlog 6743 -msg --ledgerid '-1907126707656498384'
Scan entry log 6743 (1a57.log) for LedgerId -1907126707656498384
--------- Lid=-1907126707656498384, Eid=3544957636362514976, ByteOffset=933543110, EntrySize=21842 ---------
Type:           DATA
LastConfirmed:  -1691195232188242555
Data:

00000000 31 2C 33 30 30 22 2C 22 62 69 64 5F 6C 6F 67 31 1,300","hoge_log1
00000010 33 37 22 3A 22 5B 31 31 E6 9C 88 20 31 38 E6 97 37":"[11... 18..
00000020 A5 20 32 32 E6 99 82 20 34 32 E5 88 86 5D 20 74 . 22... 42...] t
00000030 63 61 61 31 38 31 35 20 E8 87 AA E5 8B 95 E5 85 cbb1912 ........
00000040 A5 E6 9C AD E3 80 82 20 31 2C 33 30 30 22 2C 22 ....... 1,300","
00000050 62 69 64 5F 6C 6F 67 31 33 38 22 3A 22 5B 31 31 hoge_log138":"[11
.
.
.


$ sudo bookkeeper shell listledgers |sort -n|head
298020
298436
321006
328362
328722
329130
329148
329161
370452
383428


$ sudo bookkeeper shell ledgermetadata -ledgerid "-1907126707656498384"
Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsException: No such ledger exists
	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:378)
	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithLedgerManagerFactory(MetadataDrivers.java:413)
	at org.apache.bookkeeper.bookie.BookieShell$LedgerMetadataCmd.runCmd(BookieShell.java:1063)
	at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:232)
	at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2816)
	at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2907)
Caused by: java.util.concurrent.ExecutionException: org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsException: No such ledger exists
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at org.apache.bookkeeper.bookie.BookieShell.printLedgerMetadata(BookieShell.java:1017)
	at org.apache.bookkeeper.bookie.BookieShell$LedgerMetadataCmd.lambda$runCmd$0(BookieShell.java:1067)
	at org.apache.bookkeeper.meta.MetadataDrivers.lambda$runFunctionWithLedgerManagerFactory$2(MetadataDrivers.java:415)
	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:373)
	... 5 more
Caused by: org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsException: No such ledger exists
	at org.apache.bookkeeper.client.BKException.create(BKException.java:70)
	at org.apache.bookkeeper.bookie.BookieShell$ReadMetadataCallback.operationComplete(BookieShell.java:1037)
	at org.apache.bookkeeper.bookie.BookieShell$ReadMetadataCallback.operationComplete(BookieShell.java:1022)
	at org.apache.bookkeeper.meta.AbstractZkLedgerManager$3.processResult(AbstractZkLedgerManager.java:398)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$19$1.processResult(ZooKeeperClient.java:994)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:575)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:508)
```

**Comment by sijie** [comment]
@hrsakai it seems that the ledger doesn't exist in zookeeper (metadata store). but the entry in the entry log seems to be corrupted. Can you use `readlog` to check a few more entries before and after that "corrupted" entry in the same log? Maybe you can also use `readlog` to dump the list of entries (without entry payload) and share it here. We can use that to figure out what entry is corrupted and figure out a correct fix for it.

**Comment by hrsakai** [comment]
@sijie 
Thank you for your reply.
Here is the result of `bookkeeper shell readlog 6743`.
[readlog_6743.txt](https://github.com/apache/bookkeeper/files/3285405/readlog_6743.txt)

**Comment by massakam** [comment]
@sijie I don't know why there is a ledger whose id is a negative number, but I fixed `GarbageCollectorThread` so that it does not stop if compaction of a specific entry log fails.
https://github.com/apache/bookkeeper/pull/2121
What do you think about this change?
