### ISSUE TITLE
Test 'ListBookiesCommand ' is failing

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2124]
Test are failing on CI on current master on test ListBookiesCommand due to #2114 which is apparently flaky

```
2019-07-17 08:06:48,027 - ERROR - [main:DiscoveryCommand@61] - Fail to process command 'list'
java.lang.NullPointerException
	at org.apache.bookkeeper.common.concurrent.FutureUtils.result(FutureUtils.java:72)
	at org.apache.bookkeeper.common.concurrent.FutureUtils.result(FutureUtils.java:61)
	at org.apache.bookkeeper.tools.cli.commands.bookies.ListBookiesCommand.run(ListBookiesCommand.java:103)
	at org.apache.bookkeeper.tools.cli.commands.bookies.ListBookiesCommand.run(ListBookiesCommand.java:39)
	at org.apache.bookkeeper.tools.cli.helpers.DiscoveryCommand.apply(DiscoveryCommand.java:57)
	at org.apache.bookkeeper.tools.cli.helpers.ClientCommand.apply(ClientCommand.java:54)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:94)
	at org.apache.bookkeeper.tools.common.BKCommand.lambda$apply$0(BKCommand.java:49)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:224)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:51)
	at org.apache.bookkeeper.tools.cli.commands.bookies.ListBookiesCommandTest.testCommand(ListBookiesCommandTest.java:157)
	at org.apache.bookkeeper.tools.cli.commands.bookies.ListBookiesCommandTest.testListNoArgs(ListBookiesCommandTest.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUn
```

**Comment by eolivelli** [comment]
@mino181295 can you please take a look ?
this is breaking  pull request validation

**Comment by eolivelli** [comment]
CI is broken
"unable to access 'https://github.com/apache/bookkeeper.git/': Could not resolve host: github.com"
