### ISSUE TITLE
KeeperErrorCode = NoNode

### ISSUE THREAD

**Issue by ghost** [apache/bookkeeper#2170]
**BUG REPORT**
```
docker exec -it  pulsar__192_168_5_55 ./bin/bookkeeper shell lostbookierecoverydelay -get
JMX enabled by default
04:15:28.905 [main] ERROR org.apache.bookkeeper.meta.ZkLedgerUnderreplicationManager - Error while getting LostBookieRecoveryDelay
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /ledgers/underreplication/lostBookieRecoveryDelay
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:114) ~[org.apache.pulsar-pulsar-zookeeper-2.4.1.jar:2.4.1]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[org.apache.pulsar-pulsar-zookeeper-2.4.1.jar:2.4.1]
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1221) ~[org.apache.pulsar-pulsar-zookeeper-2.4.1.jar:2.4.1]
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient.access$2701(ZooKeeperClient.java:70) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$17.call(ZooKeeperClient.java:947) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$17.call(ZooKeeperClient.java:941) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
```

***To Reproduce***

1. start a docker pulsar standalone 
2. execute above command

***Expected behavior***

Printing a delay or at least not print a stack trace

***Additional context***

pulsar:2.4.1

**Comment by Ghatage** [comment]
Looks like this command was executed before the Auditor was initialized.
@pouledodue can you please check if the logs show the following error message: 
`Error while initializing LostBookieRecoveryDelay`

If you're blocked on this, as a work around you could quickly check if Auditor is up and running with this command:
`./bin/bookkeeper shell whoisauditor`
And then re-try what you were trying to do.

As for the actual issue, the throwing of the exception is expected.
But perhaps not for a NoNodeException. We could check if the zkPath exists and print another message instead of the stack trace. What do you think @jvrao @sijie @reddycharan ?

**Comment by sijie** [comment]
@Ghatage sounds like a good suggestion. Are you interested in sending out a pull request for the enhancement?

**Comment by reddycharan** [comment]
@Ghatage yes it makes sense to suppress the callstacktrace and print the appropriate error message.
