### ISSUE TITLE
NPE at TestLongZkLedgerIdGenerator.testGenerateLedgerId

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#218]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

I found the failed test case in CI build. https://builds.apache.org/job/bookkeeper-precommit-pullrequest/90

- What did you expect to see?

The test should pass.

- What did you see instead?

`
2017-06-28 23:28:33,840 - ERROR - [Thread-4:NIOServerCnxnFactory$1@92] - Thread Thread[Thread-4,5,main] died
java.lang.NullPointerException
	at org.apache.bookkeeper.meta.LongZkLedgerIdGenerator.generateLongLedgerId(LongZkLedgerIdGenerator.java:198)
	at org.apache.bookkeeper.meta.LongZkLedgerIdGenerator.createHOBPathAndGenerateId(LongZkLedgerIdGenerator.java:147)
	at org.apache.bookkeeper.meta.LongZkLedgerIdGenerator.generateLongLedgerId(LongZkLedgerIdGenerator.java:186)
	at org.apache.bookkeeper.meta.LongZkLedgerIdGenerator.generateLongLedgerId(LongZkLedgerIdGenerator.java:182)
	at org.apache.bookkeeper.meta.LongZkLedgerIdGenerator.generateLedgerId(LongZkLedgerIdGenerator.java:320)
`

**Comment by sijie** [comment]
it seems to be flaky test. remove it from 4.5.0 and mark it as 'help-needed'

**Comment by sijie** [comment]
moved this to 4.7.

**Comment by sijie** [comment]
Close it since it is an old flaky test
