### ISSUE TITLE
testAutoRecoverySessionLoss is flaky and ends with a NullPointerException on Jenkins

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2234]
**BUG REPORT**

Today I have seen this error on Jenkins

***Describe the bug***
```
4.571 s  <<< ERROR!
java.lang.NullPointerException
	at org.apache.bookkeeper.replication.AutoRecoveryMainTest.testAutoRecoverySessionLoss(AutoRecoveryMainTest.java:104)

2020-01-06\T\13:52:43.232 [ERROR] testAutoRecoverySessionLoss(org.apache.bookkeeper.replication.AutoRecoveryMainTest)  Time elapsed: 2.333 s  <<< ERROR!
java.lang.NullPointerException
	at org.apache.bookkeeper.replication.AutoRecoveryMainTest.testAutoRecoverySessionLoss(AutoRecoveryMainTest.java:104)

2020-01-06\T\13:52:43.233 [ERROR] testAutoRecoverySessionLoss(org.apache.bookkeeper.replication.AutoRecoveryMainTest)  Time elapsed: 2.461 s  <<< ERROR!
java.lang.NullPointerException
	at org.apache.bookkeeper.replication.AutoRecoveryMainTest.testAutoRecoverySessionLoss(AutoRecoveryMainTest.java:104)
```

***To Reproduce***

I can't reproduce the problem consistently

**Comment by shoothzj** [comment]
closed by hard to reproduce, and now github ci works well.
