### ISSUE TITLE
org.apache.bookkeeper.bookie.TestEntryLog is very flaky (expecially on GitHub Actions machines)

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2260]
org.apache.bookkeeper.bookie.TestEntryLog test fails very often on GitHub actions, this is very annoying for contributors

```
ERROR] Tests run: 28, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 10.731 s <<< FAILURE! - in org.apache.bookkeeper.bookie.TestEntryLog
[ERROR] testGetEntryLogsSet(org.apache.bookkeeper.bookie.TestEntryLog)  Time elapsed: 0.033 s  <<< FAILURE!
java.lang.AssertionError: expected:<[0, 1]> but was:<[0]>
	at org.apache.bookkeeper.bookie.TestEntryLog.testGetEntryLogsSet(TestEntryLog.java:442)

[ERROR] testGetEntryLogsSet(org.apache.bookkeeper.bookie.TestEntryLog)  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.AssertionError: expected:<[0, 1]> but was:<[0]>
	at org.apache.bookkeeper.bookie.TestEntryLog.testGetEntryLogsSet(TestEntryLog.java:442)

[ERROR] testGetEntryLogsSet(org.apache.bookkeeper.bookie.TestEntryLog)  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.AssertionError: expected:<[0, 1]> but was:<[0]>
	at org.apache.bookkeeper.bookie.TestEntryLog.testGetEntryLogsSet(TestEntryLog.java:442)
```

**Comment by eolivelli** [comment]
@reddycharan can you take a look please ?

cc @rdhabalia

**Comment by eolivelli** [comment]
I think that the problem is that this test is using an "entryLogger" variable that can be created by any of the other '@Test' methods.
A good fix would be to re-inizialize that variable, like how it is done in most of the other test methods in that file

```
**
     * Test the getEntryLogsSet() method.
     */
    @Test
    public void testGetEntryLogsSet() throws Exception {
        // create some entries
        EntryLogManagerBase entryLogManagerBase = ((EntryLogManagerBase) entryLogger.getEntryLogManager());
        assertEquals(Sets.newHashSet(), entryLogger.getEntryLogsSet());

        entryLogManagerBase.createNewLog(EntryLogger.UNASSIGNED_LEDGERID);
        entryLogManagerBase.flushRotatedLogs();

        assertEquals(Sets.newHashSet(0L, 1L), entryLogger.getEntryLogsSet());

        entryLogManagerBase.createNewLog(EntryLogger.UNASSIGNED_LEDGERID);
        entryLogManagerBase.flushRotatedLogs();

        assertEquals(Sets.newHashSet(0L, 1L, 2L), entryLogger.getEntryLogsSet());
    }
```
