### ISSUE TITLE
Bookie shutdown due to  OutOfDirectMemoryError 

### ISSUE THREAD

**Issue by aloyszhang** [apache/bookkeeper#2269]
**BUG REPORT**
Bookie shutdown due to  OutOfDirectMemoryError 
***Describe the bug***
Bookie shutdown when client continuous send message. 
```
ERROR [bookie-io-1-19:BookieRequestHandler@70] - Unhandled exception occurred in I/O thread or handler
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 21474836480, max: 21474836480)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:655)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:610)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:769)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:745)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
        at io.netty.buffer.PoolArena.reallocate(PoolArena.java:397)
        at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118)
        at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:299)
        at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:278)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1103)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1096)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1087)
        at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:93)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

```

***To Reproduce***
In my case,  there are 4 bookies  start with the following configuration.
bkenv.sh
```
BOOKIE_MAX_HEAP_MEMORY=10g
BOOKIE_MIN_HEAP_MEMORY=10g
BOOKIE_MAX_DIRECT_MEMORY=20g
```
bk_server.sh
```
journalDirectories=/data2/bookkeeper/journal,/data3/bookkeeper/journal,/data4/bookkeeper/journal
ledgerDirectories=/data1/bk-data,/data5/bk-data,/data7/bk-data,/data8/bk-data,/data9/bk-data
```
Directory data1,data2,data3,data4,data5,data6,data7,date8,data9 are on different disk with  individual disk driver. 
Then start client (actuallly  pulsar) to send message by pulsar-perf tool with the command :
`bin/pulsar-perf produce -threads 6 -u pulsar://10.56.204.197:6650,10.56.204.198:6650,10.56.205.196:6650 -o 10000 -n 1 -s 1000 -r 3000000 persistent://tenant-bk/namespace-bk/topic-bk`

***Expected behavior***

BookKeeper should have mechanism of  rate limit to avoid OutOfDirectMemoryError happend.

***Screenshots***
![image](https://user-images.githubusercontent.com/48062889/75014840-3357c480-54c2-11ea-978b-0d5553e01c6e.png)

**Comment by eolivelli** [comment]
Which version of BK do you have?

**Comment by eolivelli** [comment]
Are you able to reproduce the problem with a single bookie ?
I mean, in order to create a simpler reproducer ?

**Comment by aloyszhang** [comment]
This problem happens when run pulsar on BookKeeper with ensemble 3, write quorum 3 and ack quorum 2.  Data are send to 3 bookies at the same time,  so ,I think the same problem will happeds with a single bookie.

**Comment by eolivelli** [comment]
We have a few features to prevent this situation. 
Are you writing huge messages ?
Are you running the Bookie with the configuration shipped with Pulsar or the default values on "master" branch ?
You can try to tune the Bookie using Pulsar suggested values.

You can check all tunables about the maximum number of concurrent writes (pendingAdds) in this file:
https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java#L198

**Comment by aloyszhang** [comment]
Thanks ， I'll try.

**Comment by RaulGracia** [comment]
@aloyszhang @eolivelli I have seen this problem as well. In our case, we have prevented this from happening by using `InterleavedLedgerStorage` instead of the default one (`SortedLedgerStorage`), as it does not contain `EntryMemTable` objects that seem to use significant amount of memory (tested with Bookkeeper 4.9.2). Of course, this decision comes at the cost of read performance, but in our case we can afford it, as we only read from Bookkeeper for recovery after a crash. Since we shifted the ledger type, we have not seen more memory issues like this.

**Comment by aloyszhang** [comment]
Thanks for your suggestion @RaulGracia 
Since I wanna to run Pulsar on BookKeeper. 
I turn configuration to Pulsar suggested values which take `DbLedgerStorage` as Ledger Storage as  @eolivelli  suggested. 
It runs well for the passed few days.

**Comment by dreamcatchernick** [comment]
hi @aloyszhang  i also saw this problem a few days ago. We are using pulsar 2.6.0， could you please tell me how to solve this issue?

**Comment by aloyszhang** [comment]
@dreamcatchernick use `DbLedgerStorage`  instead of `SortedLedgerStorage `

**Comment by sunshujie1990** [comment]
> hi @aloyszhang i also saw this problem a few days ago. We are using pulsar 2.6.0， could you please tell me how to solve this issue?

@dreamcatchernick Have your problems finally been solved？

**Comment by yws-tracy** [comment]
> hi @aloyszhang i also saw this problem a few days ago. We are using pulsar 2.6.0， could you please tell me how to solve this issue?

I met the same problem,  was your problems finally solved？

**Comment by yws-tracy** [comment]
> 
@sunshujie1990  we met the same problem, was your problems finally solved？ we use DbLedgerStorage
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/34879511/183294702-152a341a-9bf2-40f3-a538-8142d49e0181.png">

bookkeeper version:  4.10.0
bookie conf:
```
apiVersion: v1
data:
  PULSAR_GC: |
    -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=4 -XX:ConcGCThreads=4 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/pulsar/pulsar.hprof -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintHeapAtGC -verbosegc -Xloggc:/var/log/bookie-gc.log -XX:G1LogLevel=finest
  PULSAR_MEM: |
    -Xms32g -Xmx32g -XX:MaxDirectMemorySize=32g
  PULSAR_PREFIX_dbStorage_readAheadCacheMaxSizeMb: "5120"
  PULSAR_PREFIX_journalDirectories: /pulsar/data/bookkeeper/journal
  PULSAR_PREFIX_numAddWorkerThreads: "4"
  PULSAR_PREFIX_numReadWorkerThreads: "16"
  autoRecoveryDaemonEnabled: "false"
  dbStorage_rocksDB_blockCacheSize: "536870912"
  dbStorage_rocksDB_writeBufferSizeMB: "1024"
  dbStorage_writeCacheMaxSizeMb: "5120"
  httpServerEnabled: "true"
  httpServerPort: "8000"
  journalDirectories: /pulsar/data/bookkeeper/journal
  journalMaxBackups: "0"
  ledgerDirectories: /pulsar/data/bookkeeper/ledgers
  statsProviderClass: org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider
  useHostNameAsBookieID: "true"
  zkLedgersRootPath: /ledgers
```
cc @sijie  is it a bug of bookkeeper in 4.10.0 version ?   any reply appreciate in adavance
