### ISSUE TITLE
BookKeeper is not compatible with ZookKeeper 3.6.0

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2292]
in ZKRegistrationManager  we are using the Utility function  org.apache.zookeeper.ZKUtil.deleteRecursive that has been changed in 3.6.0.

***To Reproduce***
Use ZooKeeper 3.6.0 in a project that is also using BookKeeper 4.10.0
(like https://github.com/diennea/herddb/pull/581) 

BookKeeperAdmin won't be able to work.

```
java.lang.NoSuchMethodError: org.apache.zookeeper.ZKUtil.deleteRecursive(Lorg/apache/zookeeper/ZooKeeper;Ljava/lang/String;)V
	at org.apache.bookkeeper.discover.ZKRegistrationManager.format(ZKRegistrationManager.java:513)
	at org.apache.bookkeeper.client.BookKeeperAdmin.lambda$format$3(BookKeeperAdmin.java:1194)
	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:370)
	at org.apache.bookkeeper.client.BookKeeperAdmin.format(BookKeeperAdmin.java:1167)

```
***Expected behavior***
BookKeeperAdmin should be able to "format" the cluster

**Comment by eolivelli** [comment]
I have created an issue in ZooKeeper
https://issues.apache.org/jira/browse/ZOOKEEPER-3763

**Comment by eolivelli** [comment]
With ZK 3.6.1 we won't have this problem anymore, 
see
https://github.com/apache/zookeeper/pull/1287
