### ISSUE TITLE
ListBookiesCommand.printBookies throws NullPointerException if bookie DNS name can't be resolved

### ISSUE THREAD

**Issue by sntfrc** [apache/bookkeeper#2371]
**BUG REPORT**

***Description***

"bookkeeper listbookies -a" crashes on unresolvable DNS names for a bookie, instead of going on to print other bookies.

`java.lang.NullPointerException
        at org.apache.bookkeeper.tools.cli.helpers.CommandHelpers.getBookieSocketAddrStringRepresentation(CommandHelpers.java:46)
        at org.apache.bookkeeper.tools.cli.commands.bookies.ListBookiesCommand.printBookies(ListBookiesCommand.java:119)
        at org.apache.bookkeeper.tools.cli.commands.bookies.ListBookiesCommand.run(ListBookiesCommand.java:108)
        at org.apache.bookkeeper.tools.cli.commands.bookies.ListBookiesCommand.run(ListBookiesCommand.java:39)
        at org.apache.bookkeeper.tools.cli.helpers.DiscoveryCommand.apply(DiscoveryCommand.java:57)
        at org.apache.bookkeeper.tools.cli.helpers.ClientCommand.apply(ClientCommand.java:60)
        at org.apache.bookkeeper.bookie.BookieShell$ListBookiesCmd.runCmd(BookieShell.java:1142)
        at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:223)
        at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:1976)
        at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2067)`

***To Reproduce***

1. Remove one hostname-identified bookie's DNS A record
2. Wait for DNS cache to expire, or flush
3. Issue the command: ./bookkeeper listbookies -a

***Expected behavior***

I expected to see the bookie hostname without any IP address (or a more meaningful warning) but anyway it should go on to printing the other bookies' instead of crashing.

**Comment by rudy2steiner** [comment]
I'd like to help!

**Comment by eolivelli** [comment]
Cool.
Looking for you patch

**Comment by Ghatage** [comment]
This seems to be closed under #2380.
Please reopen this / open a new issue if you find it not to be the case.
