### ISSUE TITLE
java.lang.NullPointerException with  metadataServiceUri = zk:///ledgers (Default on Docker image)

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2463]
***Describe the bug***
if you configure a bad metadata service uri you can this error

java.lang.NullPointerException
	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.getZKServersFromServiceUri(ZKMetadataDriverBase.java:64)
	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:186)
	at org.apache.bookkeeper.meta.zk.ZKMetadataBookieDriver.initialize(ZKMetadataBookieDriver.java:60)
	at org.apache.bookkeeper.bookie.Bookie.instantiateMetadataDriver(Bookie.java:1080)
	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:698)
	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:140)
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:108)
	at org.apache.bookkeeper.server.service.BookieService.<init>(BookieService.java:52)
	at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:313)
	at org.apache.bookkeeper.server.Main.doMain(Main.java:226)
	at org.apache.bookkeeper.server.Main.main(Main.java:208)
***To Reproduce***

docker run apache/bookkeeper:4.11.1

***Expected behavior***

A clearer error message like 'Invalid metadata service URI"

**Comment by eolivelli** [comment]
@nicoloboschi PTAL

**Comment by nicoloboschi** [comment]
I can take care of it

**Comment by nicoloboschi** [comment]
@eolivelli maybe we should change default zkServer param? I'd like ready-to-run solution, like 'localhost'? I don't really know BK docker container use cases

Otherwise we may add some useful logs when the container starts, explaining where to set zkserver parameter

**Comment by eolivelli** [comment]
The problem is not about docker. The problem us the NPE.
We should report a better error.

No one will ever run the docker image without ZK
