### ISSUE TITLE
NullPointerException during the stop of a BookKeeper with BookKeeper Stream Storage Server

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2505]
**BUG REPORT**

***Describe the bug***

When you stop a Bookie with the StreamStorage server enabled you can see a scary NullPointerException.

We should avoid to throw the NPE, that is usually the symptom of a bug

***To Reproduce***

1. Start a bookie with `extraServerComponents=org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent`
2. Shutdown the bookie

You can see this error:

```
2020-12-02 11:04:24,962 - ERROR - [component-shutdown-thread:ComponentStarter$ComponentShutdownHook@51] - Failed to close component bookie-server in shutdown hook gracefully, Exiting anyway
java.lang.NullPointerException
	at org.apache.bookkeeper.stream.server.service.RegistrationStateService.doClose(RegistrationStateService.java:107)
	at org.apache.bookkeeper.common.component.AbstractLifecycleComponent.close(AbstractLifecycleComponent.java:123)
	at org.apache.bookkeeper.common.component.LifecycleComponentStack.lambda$close$6(LifecycleComponentStack.java:154)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
	at org.apache.bookkeeper.common.component.LifecycleComponentStack.close(LifecycleComponentStack.java:154)
	at org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent.doClose(StreamStorageLifecycleComponent.java:59)
	at org.apache.bookkeeper.common.component.AbstractLifecycleComponent.close(AbstractLifecycleComponent.java:123)
	at org.apache.bookkeeper.common.component.LifecycleComponentStack.lambda$close$6(LifecycleComponentStack.java:154)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
	at org.apache.bookkeeper.common.component.LifecycleComponentStack.close(LifecycleComponentStack.java:154)
	at org.apache.bookkeeper.common.component.ComponentStarter$ComponentShutdownHook.run(ComponentStarter.java:47)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by rudy2steiner** [comment]
I'll work on it
