### ISSUE TITLE
There is no DockerHub image for 4.12.1

### ISSUE THREAD

**Issue by marcioapm** [apache/bookkeeper#2601]
**BUG REPORT**

***Describe the bug***

There is no DockerHub image for 4.12.1

***To Reproduce***

1. Go to https://hub.docker.com/r/apache/bookkeeper/tags?page=1&ordering=last_updated&name=4.12
2. Observe there is no 4.12.1 image

***Expected behavior***

There is a 4.12.1 image

**Comment by eolivelli** [comment]
I have started a thread on ASK Infra slack channel, in order to ask for logs

**Comment by eolivelli** [comment]
I still have to much info to share

```
[0m[91m+ wget -q https://archive.apache.org/dist/bookkeeper/bookkeeper-4.12.1/bookkeeper-server-4.12.1-bin.tar.gz
[0mThe command ‘/bin/sh -c set -x && adduser “${BK_USER}” && yum install -y java-11-openjdk-devel wget bash python sudo && mkdir -pv /opt && cd /opt && wget -q “${DISTRO_URL}” && wget -q “${DISTRO_URL}.asc” && wget -q “${DISTRO_URL}.sha512" && sha512sum -c ${DISTRO_NAME}.tar.gz.sha512 && wget https://dist.apache.org/repos/dist/release/bookkeeper/KEYS && gpg --import KEYS && gpg --batch --verify “$DISTRO_NAME.tar.gz.asc” “$DISTRO_NAME.tar.gz” && tar -xzf “$DISTRO_NAME.tar.gz” && mv bookkeeper-server-${BK_VERSION}/ /opt/bookkeeper/ && rm -rf “$DISTRO_NAME.tar.gz” “$DISTRO_NAME.tar.gz.asc” “$DISTRO_NAME.tar.gz.sha512" && wget -q https://bootstrap.pypa.io/get-pip.py && python get-pip.py && pip install zk-shell && rm -rf get-pip.py && yum remove -y wget && yum clean all && ls /usr/lib/jvm’ returned a non-zero code: 8
build hook failed! (8)
```

**Comment by eolivelli** [comment]
I tried to build it locally and it failed this way:

```
#5 99.33 Primary key fingerprint: BBE7 232D 7991 050B 54C8  EA0A DC08 637C A615 D22C
#5 99.33 + tar -xzf bookkeeper-server-4.12.1-bin.tar.gz
#5 99.94 + mv bookkeeper-server-4.12.1/ /opt/bookkeeper/
#5 99.94 + rm -rf bookkeeper-server-4.12.1-bin.tar.gz bookkeeper-server-4.12.1-bin.tar.gz.asc bookkeeper-server-4.12.1-bin.tar.gz.sha512
#5 99.96 + wget -q https://bootstrap.pypa.io/get-pip.py
#5 103.7 + python get-pip.py
#5 104.7 Traceback (most recent call last):
#5 104.7   File "get-pip.py", line 24244, in <module>
#5 104.7     main()
#5 104.7   File "get-pip.py", line 199, in main
#5 104.7     bootstrap(tmpdir=tmpdir)
#5 104.7   File "get-pip.py", line 82, in bootstrap
#5 104.7     from pip._internal.cli.main import main as pip_entry_point
#5 104.7   File "/tmp/tmp1LytFY/pip.zip/pip/_internal/cli/main.py", line 60
#5 104.7     sys.stderr.write(f"ERROR: {exc}")
#5 104.7                                    ^
#5 104.7 SyntaxError: invalid syntax
------
executor failed running [/bin/sh -c set -x     && adduser "${BK_USER}"     && yum install -y java-11-openjdk-devel wget bash python sudo    && mkdir -pv /opt     && cd /opt     && wget -q "${DISTRO_URL}"     && wget -q "${DISTRO_URL}.asc"     && wget -q "${DISTRO_URL}.sha512"     && sha512sum -c ${DISTRO_NAME}.tar.gz.sha512     && wget https://dist.apache.org/repos/dist/release/bookkeeper/KEYS     && gpg --import KEYS     && gpg --batch --verify "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz"     && tar -xzf "$DISTRO_NAME.tar.gz"     && mv bookkeeper-server-${BK_VERSION}/ /opt/bookkeeper/     && rm -rf "$DISTRO_NAME.tar.gz" "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz.sha512"     && wget -q https://bootstrap.pypa.io/get-pip.py     && python get-pip.py     && pip install zk-shell     && rm -rf get-pip.py     && yum remove -y wget     && yum clean all     && ls /usr/lib/jvm]: exit code: 1
```

The problem is about python version

**Comment by eolivelli** [comment]
@marcioapm 
the image is now available!

https://hub.docker.com/layers/apache/bookkeeper/4.12.1/images/sha256-07d1be6a035bac2d7b73f5d25926d52b7f46380fe0e172a7a1a666c4b18b02c8?context=explore

Can you please test it ?
