### ISSUE TITLE
ReadOnlyBookieTest is flaky

### ISSUE THREAD

**Issue by dlg99** [apache/bookkeeper#2665]
**BUG REPORT**

***Describe the bug***

ReadOnlyBookieTest is flaky on current master branch

***To Reproduce***

mvn clean install -DskipTests
cd bookkeeper-server/
run a few times:
 mvn test -Dtest=org.apache.bookkeeper.test.ReadOnlyBookieTest

```
[INFO] Running org.apache.bookkeeper.test.ReadOnlyBookieTest
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 31.14 s <<< FAILURE! - in org.apache.bookkeeper.test.ReadOnlyBookieTest
[ERROR] org.apache.bookkeeper.test.ReadOnlyBookieTest.testBookieContinueWritingIfMultipleLedgersPresent  Time elapsed: 4.151 s  <<< ERROR!
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
	at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
	at org.apache.bookkeeper.client.SyncCallbackUtils$SyncAddCallback.addComplete(SyncCallbackUtils.java:251)
	at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:92)
	at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:431)
	at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1799)
	at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:574)
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

[INFO]
[INFO] Results:
[INFO]
[WARNING] Flakes:
[WARNING] org.apache.bookkeeper.test.ReadOnlyBookieTest.testBookieContinueWritingIfMultipleLedgersPresent
[ERROR]   Run 1: ReadOnlyBookieTest.testBookieContinueWritingIfMultipleLedgersPresent » BKNotEnoughBookies
[INFO]   Run 2: PASS
```

**Comment by wenbingshen** [comment]
@hangc0276 Could you help close this issue because related pr #3421 has fixed it and merged. Thanks.

**Comment by shoothzj** [comment]
@wenbingshen Thanks, I have closed this issue.
