### ISSUE TITLE
Write benchmark fails with `BkNotEnoughBookiesException` even when enough bookies are available

### ISSUE THREAD

**Issue by arvindkandhare** [apache/bookkeeper#274]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?
Compile and ran the benchmark against a bookkeeper deployment.
`./bin/benchmark writes`
- What did you expect to see?
The benchmark succeeds.
- What did you see instead?
The following exception:
```
2017-07-21 22:23:44,942 - ERROR - [main:LedgerCreateOp@114] - Not enough bookies to create ledger
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException
	at org.apache.bookkeeper.client.SynchCallbackUtils.finish(SynchCallbackUtils.java:63)
	at org.apache.bookkeeper.client.BookKeeper$SyncCreateCallback.createComplete(BookKeeper.java:1252)
	at org.apache.bookkeeper.client.LedgerCreateOp.createComplete(LedgerCreateOp.java:200)
	at org.apache.bookkeeper.client.LedgerCreateOp.initiate(LedgerCreateOp.java:115)
	at org.apache.bookkeeper.client.BookKeeper.asyncCreateLedger(BookKeeper.java:626)
	at org.apache.bookkeeper.client.BookKeeper.createLedger(BookKeeper.java:711)
	at org.apache.bookkeeper.client.BookKeeper.createLedger(BookKeeper.java:685)
	at org.apache.bookkeeper.benchmark.BenchThroughputLatency.<init>(BenchThroughputLatency.java:97)
	at org.apache.bookkeeper.benchmark.BenchThroughputLatency.warmUp(BenchThroughputLatency.java:452)
	at org.apache.bookkeeper.benchmark.BenchThroughputLatency.main(BenchThroughputLatency.java:319)
```

This is because at line 445 of `BenchThroughputLatency.java` the node `readonly` is counted in available bookies too. Changing the line to 
`bookies = zk.getChildren(bookieRegistrationPath, false).size() -1;`
resolves the issue.
---------------------------------------------------------------------------------

Please label the issue with proper labels. It would help us triage the issues.

- "release/": please mark the issue with the release. 
- "type/": please mark the issue with corresponding issue type.

**Comment by sijie** [comment]
@arvindkandhare are you going to provide the fix for this?
