### ISSUE TITLE
EntryLocationIndex.getLastEntryInLedger has bug when the ledger has been deleted

### ISSUE THREAD

**Issue by StevenLuMT** [apache/bookkeeper#2927]
**BUG REPORT**

***Describe the bug***

A ledger's EntryLocationIndex has bean deleted, EntryLocationIndex.deletedLedgers contains this ledgerId,
then fence and get lac from this ledger ,then the bug will be fired

***To Reproduce***

1.  A ledger's EntryLocationIndex has bean deleted, EntryLocationIndex.deletedLedgers contains this ledgerId
2. fence and get lac from this ledger
3. the bookie throw a unexpected: IOException

***Expected behavior***

response the client NoEntry

***Screenshots***

2021-12-06 12:04:32,946 [BookieHighPriorityThread-3181-OrderedExecutor-22-0] DEBUG org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage - Found last entry for ledger 1945510 in db: -1
2021-12-06 12:04:32,946 [BookieHighPriorityThread-3181-OrderedExecutor-22-0] DEBUG org.apache.bookkeeper.bookie.storage.ldb.EntryLocationIndex - Entry not found 1945510@-1 in db index
2021-12-06 12:04:32,947 [bookie-io-1-32] TRACE org.apache.bookkeeper.proto.BookieProtoEncoding - Received request PooledSlicedByteBuf(ridx: 0, widx: 53, cap: 53/53, unwrapped: PooledUnsafeDirectByteBuf(ridx: 57, widx: 57, cap: 65536)) from channel [id: 0x53e6c6bd, L:/bk1:3181 - R:/bk2:27344] to decode.
2021-12-06 12:04:32,947 [BookieHighPriorityThread-3181-OrderedExecutor-22-0] ERROR org.apache.bookkeeper.proto.ReadEntryProcessorV3 - IOException while reading entry: -1 from ledger 1945510
java.io.IOException: org.apache.bookkeeper.bookie.EntryLogger$EntryLookupException$MissingLogFileException: Missing entryLog 0 for ledgerId 1945510, entry -1 at offset 0
	at org.apache.bookkeeper.bookie.EntryLogger.internalReadEntry(EntryLogger.java:847) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.bookie.EntryLogger.readEntry(EntryLogger.java:871) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage.getLastEntry(SingleDirectoryDbLedgerStorage.java:567) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage.getEntry(SingleDirectoryDbLedgerStorage.java:403) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage.getEntry(DbLedgerStorage.java:200) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.bookie.LedgerDescriptorImpl.readEntry(LedgerDescriptorImpl.java:161) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.bookie.BookieImpl.readEntry(BookieImpl.java:1457) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.proto.ReadEntryProcessorV3.readEntry(ReadEntryProcessorV3.java:173) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.proto.ReadEntryProcessorV3.readEntry(ReadEntryProcessorV3.java:153) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.proto.ReadEntryProcessorV3.getReadResponse(ReadEntryProcessorV3.java:216) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.proto.ReadEntryProcessorV3.executeOp(ReadEntryProcessorV3.java:262) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.proto.ReadEntryProcessorV3.safeRun(ReadEntryProcessorV3.java:258) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-20211026.071745-3.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) ~[org.apache.bookkeeper-bookkeeper-common-4.15.0-20211026.070813-4.jar:4.15.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_202]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

***Additional context***

**Comment by StevenLuMT** [comment]
bugfix in pr #2946
