### ISSUE TITLE
No network topology script is found when using script based DNS resolver.

### ISSUE THREAD

**Issue by mingyifei** [apache/bookkeeper#2929]
code:
`        BookKeeper bk = new BookKeeper("127.0.0.1:2181");
`
version: 4.15.0-SNAPSHOT(master install)

20:40:27.105 [main] ERROR org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Failed to initialize DNS Resolver org.apache.bookkeeper.net.ScriptBasedMapping, used default subnet resolver 
java.lang.RuntimeException: No network topology script is found when using script based DNS resolver.
	at org.apache.bookkeeper.net.ScriptBasedMapping$RawScriptBasedMapping.validateConf(ScriptBasedMapping.java:163) ~[bookkeeper-server-4.15.0-SNAPSHOT.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.net.AbstractDNSToSwitchMapping.setConf(AbstractDNSToSwitchMapping.java:81) ~[bookkeeper-server-4.15.0-SNAPSHOT.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.net.ScriptBasedMapping.setConf(ScriptBasedMapping.java:123) ~[bookkeeper-server-4.15.0-SNAPSHOT.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.initialize(RackawareEnsemblePlacementPolicyImpl.java:265) [bookkeeper-server-4.15.0-SNAPSHOT.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.initialize(RackawareEnsemblePlacementPolicyImpl.java:80) [bookkeeper-server-4.15.0-SNAPSHOT.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.client.BookKeeper.initializeEnsemblePlacementPolicy(BookKeeper.java:581) [bookkeeper-server-4.15.0-SNAPSHOT.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:505) [bookkeeper-server-4.15.0-SNAPSHOT.jar:4.15.0-SNAPSHOT]
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:344) [bookkeeper-server-4.15.0-SNAPSHOT.jar:4.15.0-SNAPSHOT]
	at use.BookeeperOpt.main(BookeeperOpt.java:24) [classes/:?]

**Comment by mingyifei** [comment]
![image](https://user-images.githubusercontent.com/38995810/144848483-558ac7b5-5c0d-4d8d-a366-314a4a676316.png)

**Comment by mingyifei** [comment]
what should i do?

**Comment by zymap** [comment]
It means there is no network topology script and it will going to use the default subnet resolver. I think it's just a warning and it shouldn't impact your usage.

**Comment by mingyifei** [comment]
> It means there is no network topology script and it will going to use the default subnet resolver. I think it's just a warning and it shouldn't impact your usage.

ok. I commented validateConf.
