### ISSUE TITLE
Java 11 support is incomplete, CI check for the Java 11 support is not enough

### ISSUE THREAD

**Issue by dlg99** [apache/bookkeeper#3025]
**BUG REPORT**

***Describe the bug***

***To Reproduce***

1. Make sure Java 11 is used
2. `./gradlew bookkeeper-server:test -i --tests="org.apache.bookkeeper.bookie.BookieJournalTest"`
3. tests fail, see errors

```
class javax.naming.spi.NamingManager (in unnamed module @0x40b0e47d) cannot access class jdk.internal.loader.ClassLoaderValue (in module java.base) because module java.base does not export jdk.internal.loader to unnamed module @0x40b0e47d
java.lang.IllegalAccessError: class javax.naming.spi.NamingManager (in unnamed module @0x40b0e47d) cannot access class jdk.internal.loader.ClassLoaderValue (in module java.base) because module java.base does not export jdk.internal.loader to unnamed module @0x40b0e47d
	at javax.naming.spi.NamingManager.<clinit>(NamingManager.java:86)
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:332)
	at javax.naming.directory.InitialDirContext.getURLOrDefaultInitDirCtx(InitialDirContext.java:106)
	at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:142)
	at org.apache.bookkeeper.net.DNS.reverseDns(DNS.java:83)
	at org.apache.bookkeeper.net.DNS.getHosts(DNS.java:239)
	at org.apache.bookkeeper.net.DNS.getDefaultHost(DNS.java:338)
	at org.apache.bookkeeper.net.DNS.getDefaultHost(DNS.java:354)
	at org.apache.bookkeeper.bookie.BookieImpl.getBookieAddress(BookieImpl.java:263)
	at org.apache.bookkeeper.bookie.BookieImpl.getBookieId(BookieImpl.java:243)
	at org.apache.bookkeeper.bookie.ScanAndCompareGarbageCollector.<init>(ScanAndCompareGarbageCollector.java:95)
	at org.apache.bookkeeper.bookie.GarbageCollectorThread.<init>(GarbageCollectorThread.java:160)
	at org.apache.bookkeeper.bookie.GarbageCollectorThread.<init>(GarbageCollectorThread.java:133)
	at org.apache.bookkeeper.bookie.InterleavedLedgerStorage.initializeWithEntryLogger(InterleavedLedgerStorage.java:196)
	at org.apache.bookkeeper.bookie.InterleavedLedgerStorage.initializeWithEntryLogListener(InterleavedLedgerStorage.java:160)
	at org.apache.bookkeeper.bookie.SortedLedgerStorage.initialize(SortedLedgerStorage.java:87)
	at org.apache.bookkeeper.bookie.BookieResources.createLedgerStorage(BookieResources.java:110)
	at org.apache.bookkeeper.bookie.TestBookieImpl$ResourceBuilder.build(TestBookieImpl.java:181)
	at org.apache.bookkeeper.bookie.TestBookieImpl.<init>(TestBookieImpl.java:46)
	at org.apache.bookkeeper.bookie.BookieJournalTest.createBookieAndReadJournal(BookieJournalTest.java:658)
	at org.apache.bookkeeper.bookie.BookieJournalTest.testV5Journal(BookieJournalTest.java:429)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
```

***Expected behavior***

test succeeds

***Additional context***

[Looks like add-exports is needed](https://stackoverflow.com/a/42541096/2237794) for the build and runtime (and test runtime)

**Comment by shoothzj** [comment]
closed by #3027
