### ISSUE TITLE
Flaky-test: org.apache.bookkeeper.test.BookieZKExpireTest flaked with "AssertionError: Bookie should not shutdown on losing zk session"

### ISSUE THREAD

**Issue by dlg99** [apache/bookkeeper#3059]
```
org.apache.bookkeeper.test.BookieZKExpireTest

  Test testBookieServerZKExpireBehaviour FAILED (16.1s)

  java.lang.AssertionError: Bookie should not shutdown on losing zk session
      at org.apache.bookkeeper.test.BookieZKExpireTest.testBookieServerZKExpireBehaviour(BookieZKExpireTest.java:103)


org.apache.bookkeeper.test.BookieZKExpireTest

  Test testBookieServerZKExpireBehaviour FAILED (16.1s)

  java.lang.AssertionError: Bookie should not shutdown on losing zk session
      at org.apache.bookkeeper.test.BookieZKExpireTest.testBookieServerZKExpireBehaviour(BookieZKExpireTest.java:103)


org.apache.bookkeeper.test.BookieZKExpireTest

  Test testBookieServerZKExpireBehaviour FAILED (16.1s)

  java.lang.AssertionError: Bookie should not shutdown on losing zk session
      at org.apache.bookkeeper.test.BookieZKExpireTest.testBookieServerZKExpireBehaviour(BookieZKExpireTest.java:103)


org.apache.bookkeeper.test.BookieZKExpireTest

  Test testBookieServerZKExpireBehaviour FAILED (16.1s)

  java.lang.AssertionError: Bookie should not shutdown on losing zk session
      at org.apache.bookkeeper.test.BookieZKExpireTest.testBookieServerZKExpireBehaviour(BookieZKExpireTest.java:103)


org.apache.bookkeeper.test.BookieZKExpireTest

  Test testBookieServerZKExpireBehaviour FAILED (16.1s)

  java.lang.AssertionError: Bookie should not shutdown on losing zk session
      at org.apache.bookkeeper.test.BookieZKExpireTest.testBookieServerZKExpireBehaviour(BookieZKExpireTest.java:103)



1892 tests completed, 6 failed, 21 skipped
FAILURE: Executed 1892 tests in 1h 34m (6 failed, 21 skipped)

```

**Comment by dlg99** [comment]
dup of https://github.com/apache/bookkeeper/issues/3206
