### ISSUE TITLE
TestFencing.testManyOpenParallel

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#343]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

Run TestFencing

- What did you expect to see?

TestFencing should pass

- What did you see instead?

TestFencing fails on 

testManyOpenParallel(org.apache.bookkeeper.client.TestFencing)  Time elapsed: 60.267 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at org.apache.bookkeeper.client.TestFencing.testManyOpenParallel(TestFencing.java:196)

**Comment by eolivelli** [comment]
@zhaijack @sijie @jvrao @merlimat  is this a blocker for 4.5 ?
the test is flaky but I wonder if there is something we changed that introduced "flakyness"

the test is the same as in 4.4, does anyone remember it was flaky in 4.4 too ?
if in 4.4 it was "stable" maybe we should take care of digging into the problem before releasing 4.5  as the test is about one of the core features of BK

**Comment by zhaijack** [comment]
There seems be a race condition, it is not fail every time, and while timeout, some ledgerOpenThread is waiting, and never wakeup
```
 "TestFencing-LedgerOpenThread-7" #1674 daemon prio=5 os_prio=31 tid=0x00007f840f424800 nid=0x44103 waiting on condition [0x000070002a769000]
    java.lang.Thread.State: WAITING (parking)
     at sun.misc.Unsafe.park(Native Method)
     - parking to wait for  <0x00000007abc18608> (a java.util.concurrent.CompletableFuture$Signaller)
     at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
     at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
     at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
     at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
     at org.apache.bookkeeper.client.SynchCallbackUtils.waitForResult(SynchCallbackUtils.java:40)
     at org.apache.bookkeeper.client.BookKeeper.openLedger(BookKeeper.java:1132)
     at org.apache.bookkeeper.client.TestFencing$LedgerOpenThread.run(TestFencing.java:121)
 
 "TestFencing-LedgerOpenThread-0" #1667 daemon prio=5 os_prio=31 tid=0x00007f840ddb5800 nid=0x43303 waiting on condition [0x000070002a054000]
    java.lang.Thread.State: WAITING (parking)
     at sun.misc.Unsafe.park(Native Method)
     - parking to wait for  <0x00000007aff50520> (a java.util.concurrent.CompletableFuture$Signaller)
     at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
     at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
     at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
     at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
     at org.apache.bookkeeper.client.SynchCallbackUtils.waitForResult(SynchCallbackUtils.java:40)
     at org.apache.bookkeeper.client.BookKeeper.openLedger(BookKeeper.java:1132)
     at org.apache.bookkeeper.client.TestFencing$LedgerOpenThread.run(TestFencing.java:121)

```

**Comment by sijie** [comment]
I think the race condition was introduced by `lac piggyback`.

```
2017-08-28 00:36:47,924 - INFO  - [BookKeeperClientWorker-orderedsafeexecutor-3-0:LedgerHandle@1262] - Head of the queue entryId: 28 is not lac: 28 + 1
```
