### ISSUE TITLE
Cookie compatible problem.

### ISSUE THREAD

**Issue by horizonzy** [apache/bookkeeper#3430]
**BUG REPORT**

In #3372, we introduce indexDirs in cookie. When the bookie start, it will check the indexDirs, there is a problem.

If the user already register cookie to RM before this pr, the cookie didn't contains indexDirs, cause the before version didn't contains property `indexDirs`, although user config `indexDirs` in the ServerConfiguration.

After this pr, the bookie restart, it will config indexDirs at local, when it fetch remote cookie from rm, the response cookie didn't contains indexDirs, so the check indexDirs will fail.

This is a breaking compatible problem.

https://github.com/apache/bookkeeper/blob/442e3bbad384fba9b09f8ea774e28562a8d5c6d7/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Cookie.java#L139-L153

At line 144, `null == c.indexDirs` is true.

**Comment by horizonzy** [comment]
The error stack:
```
2022-07-28T17:17:06,855 - ERROR - [main:Main@274] - Failed to build bookie server
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: Cookie [5
bookieHost: "192.168.31.216:3181"
journalDir: "/Users/horizon/Downloads/bk1/bk-txn"
ledgerDirs: "1\t/Users/horizon/Downloads/bk1/bk-data"
instanceId: "0032a00a-b32b-4ecd-9cbd-4bdffed0d816"
indexDirs: "1\t/Users/horizon/Downloads/bk1/bk-data"
] is not matching with [5
bookieHost: "192.168.31.216:3181"
journalDir: "/Users/horizon/Downloads/bk1/bk-txn"
ledgerDirs: "1\t/Users/horizon/Downloads/bk1/bk-data"
instanceId: "0032a00a-b32b-4ecd-9cbd-4bdffed0d816"
]
	at org.apache.bookkeeper.bookie.Cookie.verifyInternal(Cookie.java:165) ~[classes/:?]
	at org.apache.bookkeeper.bookie.Cookie.verify(Cookie.java:176) ~[classes/:?]
	at org.apache.bookkeeper.bookie.LegacyCookieValidation.readAndVerifyCookieFromRegistrationManager(LegacyCookieValidation.java:182) ~[classes/:?]
	at org.apache.bookkeeper.bookie.LegacyCookieValidation.checkCookies(LegacyCookieValidation.java:75) ~[classes/:?]
	at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:423) ~[classes/:?]
	at org.apache.bookkeeper.server.Main.doMain(Main.java:272) ~[classes/:?]
	at org.apache.bookkeeper.server.Main.main(Main.java:255) ~[classes/:?]
```

**Comment by StevenLuMT** [comment]
Thanks @horizonzy 
I'm following up on this issue
