### ISSUE TITLE
Upgrade to commons-lang 2.6

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#385]
We are including commons-lang.2.4.jar in bookkeeper-server package. This version is not compatible with Java9.
The Bookie runs well with commons-lang 2.6 and with Java9.
We should upgrade the packaged version to 2.6.

Actually Bookie of version 4.5.0 run on Java9 just by replacing manually the commons-lang-2.4 jar with the 2.6 jar

this is the error
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.bookkeeper.proto.BookieNettyServer.<init>(BookieNettyServer.java:115)
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:98)
	at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:418)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
	at java.base/java.lang.String.substring(String.java:1885)
	at org.apache.commons.lang.SystemUtils.getJavaVersionAsFloat(SystemUtils.java:1133)
	at org.apache.commons.lang.SystemUtils.<clinit>(SystemUtils.java:818)
	... 3 more

```

**Comment by eolivelli** [comment]
I am running in production commons-lang 2.6 + bookie on BK 4.4 since months without problems
