### ISSUE TITLE
org.apache.bookkeeper.client.TestSpeculativeRead consistently fails on Mac buils

### ISSUE THREAD

**Issue by dlg99** [apache/bookkeeper#3899]
bk 4.16.0 RC2

```
[ERROR] org.apache.bookkeeper.client.TestSpeculativeRead.testSequenceReadLocalEnsemble
[ERROR]   Run 1: TestSpeculativeRead.testSequenceReadLocalEnsemble:396 » Runtime java.net.Unkno...
[ERROR]   Run 2: TestSpeculativeRead.testSequenceReadLocalEnsemble:396 » Runtime java.net.Unkno...
[ERROR]   Run 3: TestSpeculativeRead.testSequenceReadLocalEnsemble:396 » Runtime java.net.Unkno...
```

**Comment by hangc0276** [comment]
Hi @dlg99, I run the test on my mac, and it passed. Would you please share the full stack and logs?

**Comment by dlg99** [comment]
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.148 s <<< FAILURE! - in org.apache.bookkeeper.client.TestSpeculativeRead
[ERROR] org.apache.bookkeeper.client.TestSpeculativeRead.testSequenceReadLocalEnsemble  Time elapsed: 6.145 s  <<< ERROR!
java.lang.RuntimeException:
java.net.UnknownHostException: Trying to listen on loopback address, 127.0.0.1:3181 but this is forbidden by default (see ServerConfiguration#getAllowLoopback()).
If this happen, you can consider specifying the network interface to listen on (e.g. listeningInterface=eth0) or specifying the advertised address (e.g. advertisedAddress=172.x.y.z)
	at org.apache.bookkeeper.bookie.LocalBookieEnsemblePlacementPolicy.initialize(LocalBookieEnsemblePlacementPolicy.java:68)
	at org.apache.bookkeeper.client.BookKeeper.initializeEnsemblePlacementPolicy(BookKeeper.java:579)
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:503)
	at org.apache.bookkeeper.client.BookKeeperTestClient.<init>(BookKeeperTestClient.java:48)
	at org.apache.bookkeeper.client.TestSpeculativeRead.testSequenceReadLocalEnsemble(TestSpeculativeRead.java:396)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.UnknownHostException: Trying to listen on loopback address, 127.0.0.1:3181 but this is forbidden by default (see ServerConfiguration#getAllowLoopback()).
If this happen, you can consider specifying the network interface to listen on (e.g. listeningInterface=eth0) or specifying the advertised address (e.g. advertisedAddress=172.x.y.z)
	at org.apache.bookkeeper.bookie.BookieImpl.getBookieAddress(BookieImpl.java:293)
	at org.apache.bookkeeper.bookie.BookieImpl.getBookieId(BookieImpl.java:248)
	at org.apache.bookkeeper.bookie.LocalBookieEnsemblePlacementPolicy.initialize(LocalBookieEnsemblePlacementPolicy.java:65)
	... 18 more
```

Full log: [org.apache.bookkeeper.client.TestSpeculativeRead-output.txt](https://github.com/apache/bookkeeper/files/11124385/org.apache.bookkeeper.client.TestSpeculativeRead-output.txt)

**Comment by hangc0276** [comment]
@dlg99 It looks like the loopback address problem, and the Bookie server does not allow loopback interfaces as the primary interface.
