### ISSUE TITLE
GSSAPIBookKeeperTest failed on jenkins

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#395]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

trigger pullrequest-precommit CI job

- What did you expect to see?

CI should pass

- What did you see instead?

```
java.lang.NoClassDefFoundError: org/apache/directory/api/ldap/model/entry/Entry
	at org.apache.bookkeeper.sasl.GSSAPIBookKeeperTest.startMiniKdc(GSSAPIBookKeeperTest.java:74)
Caused by: java.lang.ClassNotFoundException: org.apache.directory.api.ldap.model.entry.Entry
	at org.apache.bookkeeper.sasl.GSSAPIBookKeeperTest.startMiniKdc(GSSAPIBookKeeperTest.java:74)
```

**Comment by sijie** [comment]
marked it as 'wontfix' because it was due to code coverage plugin.
