### ISSUE TITLE
The 4.15 vesion dosen't automatically create the corresponding znode when starting in local IDE

### ISSUE THREAD

**Issue by gvanyao** [apache/bookkeeper#4031]
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /test-ledgers/available/test-bookie-1
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:118) ~[zookeeper-3.8.0.jar:3.8.0]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[zookeeper-3.8.0.jar:3.8.0]
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1347) ~[zookeeper-3.8.0.jar:3.8.0]
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$9.call(ZooKeeperClient.java:716) ~[classes/:?]
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$9.call(ZooKeeperClient.java:708) ~[classes/:?]
	at org.apache.bookkeeper.zookeeper.ZooWorker.syncCallWithRetries(ZooWorker.java:140) ~[classes/:?]
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient.create(ZooKeeperClient.java:708) ~[classes/:?]
	at org.apache.bookkeeper.discover.ZKRegistrationManager.doRegisterBookie(ZKRegistrationManager.java:266) ~[classes/:?]
	at org.apache.bookkeeper.discover.ZKRegistrationManager.registerBookie(ZKRegistrationManager.java:224) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager.doRegisterBookie(BookieStateManager.java:282) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager.doRegisterBookie(BookieStateManager.java:270) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager$2.call(BookieStateManager.java:233) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager$2.call(BookieStateManager.java:228) ~[classes/:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]
2023-07-16T17:35:37,547 - ERROR - [main:BookieImpl@716] - Couldn't register bookie with zookeeper, shutting down : 
java.util.concurrent.ExecutionException: java.io.IOException: org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /test-ledgers/available/test-bookie-1
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_211]
	at org.apache.bookkeeper.bookie.BookieImpl.start(BookieImpl.java:714) ~[classes/:?]
	at org.apache.bookkeeper.proto.BookieServer.start(BookieServer.java:122) ~[classes/:?]
	at org.apache.bookkeeper.server.service.BookieService.doStart(BookieService.java:88) ~[classes/:?]
	at org.apache.bookkeeper.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:83) ~[classes/:?]
	at org.apache.bookkeeper.common.component.LifecycleComponentStack.lambda$start$4(LifecycleComponentStack.java:144) ~[classes/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at org.apache.bookkeeper.common.component.LifecycleComponentStack.start(LifecycleComponentStack.java:144) ~[classes/:?]
	at org.apache.bookkeeper.common.component.ComponentStarter.startComponent(ComponentStarter.java:85) ~[classes/:?]
	at org.apache.bookkeeper.server.Main.doMain(Main.java:280) ~[classes/:?]
	at org.apache.bookkeeper.server.Main.main(Main.java:255) ~[classes/:?]
	at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:287) ~[classes/:?]
Caused by: java.io.IOException: org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /test-ledgers/available/test-bookie-1
	at org.apache.bookkeeper.bookie.BookieStateManager.doRegisterBookie(BookieStateManager.java:285) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager.doRegisterBookie(BookieStateManager.java:270) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager$2.call(BookieStateManager.java:233) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager$2.call(BookieStateManager.java:228) ~[classes/:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]
Caused by: org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /test-ledgers/available/test-bookie-1
	at org.apache.bookkeeper.discover.ZKRegistrationManager.doRegisterBookie(ZKRegistrationManager.java:274) ~[classes/:?]
	at org.apache.bookkeeper.discover.ZKRegistrationManager.registerBookie(ZKRegistrationManager.java:224) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager.doRegisterBookie(BookieStateManager.java:282) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager.doRegisterBookie(BookieStateManager.java:270) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager$2.call(BookieStateManager.java:233) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager$2.call(BookieStateManager.java:228) ~[classes/:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /test-ledgers/available/test-bookie-1
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:118) ~[zookeeper-3.8.0.jar:3.8.0]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[zookeeper-3.8.0.jar:3.8.0]
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1347) ~[zookeeper-3.8.0.jar:3.8.0]
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$9.call(ZooKeeperClient.java:716) ~[classes/:?]
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$9.call(ZooKeeperClient.java:708) ~[classes/:?]
	at org.apache.bookkeeper.zookeeper.ZooWorker.syncCallWithRetries(ZooWorker.java:140) ~[classes/:?]
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient.create(ZooKeeperClient.java:708) ~[classes/:?]
	at org.apache.bookkeeper.discover.ZKRegistrationManager.doRegisterBookie(ZKRegistrationManager.java:266) ~[classes/:?]
	at org.apache.bookkeeper.discover.ZKRegistrationManager.registerBookie(ZKRegistrationManager.java:224) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager.doRegisterBookie(BookieStateManager.java:282) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager.doRegisterBookie(BookieStateManager.java:270) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager$2.call(BookieStateManager.java:233) ~[classes/:?]
	at org.apache.bookkeeper.bookie.BookieStateManager$2.call(BookieStateManager.java:228) ~[classes/:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]

**Comment by shoothzj** [comment]
@gvanyao How do you start it in your local IDE? Could you please describe it and try it on master branch? Thanks :)

**Comment by gvanyao** [comment]
@shoothzj Thanks, it's solved
