### ISSUE TITLE
Test failure in UpdateLedgerOpTest

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#414]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?
run unit tests
- What did you expect to see?
tests passed
- What did you see instead?
```
Running org.apache.bookkeeper.client.UpdateLedgerOpTest
Tests run: 4, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 2.822 sec <<< FAILURE! - in org.apache.bookkeeper.client.UpdateLedgerOpTest
testLimitLessThanTotalLedgers(org.apache.bookkeeper.client.UpdateLedgerOpTest)  Time elapsed: 0.741 sec  <<< ERROR!
java.net.UnknownHostException: Trying to listen on loopback address, 127.0.0.1:3181 but this is forbidden by default (see ServerConfiguration#getAllowLoopback())
	at org.apache.bookkeeper.client.UpdateLedgerOpTest.testLimitLessThanTotalLedgers(UpdateLedgerOpTest.java:127)

testManyLedgers(org.apache.bookkeeper.client.UpdateLedgerOpTest)  Time elapsed: 0.329 sec  <<< ERROR!
java.net.UnknownHostException: Trying to listen on loopback address, 127.0.0.1:3181 but this is forbidden by default (see ServerConfiguration#getAllowLoopback())
	at org.apache.bookkeeper.client.UpdateLedgerOpTest.testManyLedgers(UpdateLedgerOpTest.java:87)

testChangeEnsembleAfterRenaming(org.apache.bookkeeper.client.UpdateLedgerOpTest)  Time elapsed: 0.167 sec  <<< ERROR!
java.net.UnknownHostException: Trying to listen on loopback address, 127.0.0.1:3181 but this is forbidden by default (see ServerConfiguration#getAllowLoopback())
	at org.apache.bookkeeper.client.UpdateLedgerOpTest.testChangeEnsembleAfterRenaming(UpdateLedgerOpTest.java:174)

Results :
Tests in error: 
  UpdateLedgerOpTest.testChangeEnsembleAfterRenaming:174 » UnknownHost Trying to...
  UpdateLedgerOpTest.testLimitLessThanTotalLedgers:127 » UnknownHost Trying to l...
  UpdateLedgerOpTest.testManyLedgers:87 » UnknownHost Trying to listen on loopba...

```

**Comment by zhaijack** [comment]
looking into this issue. seems         `baseConf.setAllowLoopback(true);` not take effect in my env.

**Comment by zhaijack** [comment]
The problem is that the configuration in baseConf not get the wanted value after `new ServerConfiguration(baseConf)`.
In the test, we setAllowLoopback(true), and thought it always true, but seems acturally not. 
```
public UpdateLedgerOpTest() {
    super(3);
    baseConf.setAllowLoopback(true);  < === here set true
    baseConf.setGcWaitTime(100000);
}
\
testManyLedgers() 
\
BookieSocketAddress curBookieId = Bookie.getBookieAddress(baseConf);
\
if (addr.getSocketAddress().getAddress().isLoopbackAddress()
    && !conf.getAllowLoopback()) {  < === getAllowLoopback get false, but we want it to be true.
    throw new UnknownHostException("Trying to listen on loopback address, "
            + addr + " but this is forbidden by default "
            + "(see ServerConfiguration#getAllowLoopback())");
}
```
Add some log to trace and debug, Here is the place that the value in baseConf turns into unwanted at here:
``` 
protected ServerConfiguration newServerConfiguration(int port, String zkServers, File journalDir, File[] ledgerDirs) {
    ServerConfiguration conf = new ServerConfiguration(baseConf);  < ===  
    conf.setBookiePort(port);
    conf.setZkServers(zkServers);
    LOG.info("baseConf: getAllowLoopBack: {} ", baseConf.getAllowLoopback()); < == print true
    conf.setAllowLoopback(true);  < == after this call, baseConf value also changed.
    LOG.info("baseConf: getAllowLoopBack: {} ", baseConf.getAllowLoopback()); < == print false
    LOG.info("newConf: getAllowLoopBack: {} ", conf.getAllowLoopback());
    conf.setJournalDirName(journalDir.getPath());

    String[] ledgerDirNames = new String[ledgerDirs.length];
    for (int i=0; i<ledgerDirs.length; i++) {
        ledgerDirNames[i] = ledgerDirs[i].getPath();
    }
    conf.setLedgerDirNames(ledgerDirNames);
    return conf;
}
```

**Comment by zhaijack** [comment]
discussed this issue with @sijie on slack channel, and work together to figure out the reason. Thanks @sijie for the help.
Here is how [CompositeConfiguration](https://commons.apache.org/proper/commons-configuration/apidocs/org/apache/commons/configuration2/CompositeConfiguration.html) works: 
```
CompositeConfiguration allows you to add multiple Configuration objects to an aggregated configuration. If you add Configuration1, and then Configuration2, any properties shared will mean that the value defined by Configuration1 will be returned. If Configuration1 doesn't have the property, then Configuration2 will be checked. You can add multiple different types or the same type of properties file.

When querying properties the order in which child configurations have been added is relevant. To deal with property updates, a so-called in-memory configuration is used. Per default, such a configuration is created automatically. All property writes target this special configuration. There are constructors which allow you to provide a specific in-memory configuration. If used that way, the in-memory configuration is always the last one in the list of child configurations. This means that for query operations all other configurations take precedence.
```
To achieve this goal, setProperty will first [clearProperty](https://github.com/apache/commons-configuration/blob/trunk/src/main/java/org/apache/commons/configuration2/CompositeConfiguration.java#L361) and then do addProperty.

While in our use case:
ServerConfiguration conf = new ServerConfiguration(baseConf); 
conf.setAllowLoopback(true);  < == this will clear the value in baseConf first, and cause we get un-wanted value.
