### ISSUE TITLE
Test failure in UpdateCookieCmdTest

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#415]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?
run unit-test
- What did you expect to see?
test pass
- What did you see instead?
errors:
```
Running org.apache.bookkeeper.bookie.UpdateCookieCmdTest
Tests run: 6, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 1.118 sec <<< FAILURE! - in org.apache.bookkeeper.bookie.UpdateCookieCmdTest
testUpdateCookieIpAddressToHostname(org.apache.bookkeeper.bookie.UpdateCookieCmdTest)  Time elapsed: 0.632 sec  <<< ERROR!
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /ledgers/cookies/127.0.0.1:61971
	at org.apache.bookkeeper.bookie.UpdateCookieCmdTest.updateCookie(UpdateCookieCmdTest.java:190)
	at org.apache.bookkeeper.bookie.UpdateCookieCmdTest.testUpdateCookieIpAddressToHostname(UpdateCookieCmdTest.java:56)

testUpdateCookieHostnameToIpAddress(org.apache.bookkeeper.bookie.UpdateCookieCmdTest)  Time elapsed: 0.071 sec  <<< ERROR!
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /ledgers/cookies/127.0.0.1:61991
	at org.apache.bookkeeper.bookie.UpdateCookieCmdTest.updateCookie(UpdateCookieCmdTest.java:190)
	at org.apache.bookkeeper.bookie.UpdateCookieCmdTest.testUpdateCookieHostnameToIpAddress(UpdateCookieCmdTest.java:64)

testWhenBothIPaddressAndHostNameCookiesExists(org.apache.bookkeeper.bookie.UpdateCookieCmdTest)  Time elapsed: 0.061 sec  <<< ERROR!
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /ledgers/cookies/127.0.0.1:61998
	at org.apache.bookkeeper.bookie.UpdateCookieCmdTest.updateCookie(UpdateCookieCmdTest.java:190)
	at org.apache.bookkeeper.bookie.UpdateCookieCmdTest.testWhenBothIPaddressAndHostNameCookiesExists(UpdateCookieCmdTest.java:107)

Results :

Tests in error: 
  UpdateCookieCmdTest.testUpdateCookieHostnameToIpAddress:64->updateCookie:190 » NoNode
  UpdateCookieCmdTest.testUpdateCookieIpAddressToHostname:56->updateCookie:190 » NoNode  UpdateCookieCmdTest.testWhenBothIPaddressAndHostNameCookiesExists:107->updateCookie:190 » NoNode
```

**Comment by ivankelly** [comment]
@zhaijack Closing this. I haven't seen this failure in a long time, so either it's fixed, or wasn't a problem originally. We can reopen if this proves to be a problem again.
