### ISSUE TITLE
Stats Provider jars not included in "server-bin" package 

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#458]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Stats Provider jars not included in "server-bin" package, this will cause error for user to use the release binrary. It would be good to provide a "-all" package besides "server-bin" package.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have

3. Provide any additional detail on your proposed use case for this feature.

bk_server.conf contains the configuration of "statsProviderClass", and user could choose provider between PrometheusMetricsProvider, CodahaleMetricsProvider and Twitter finagle/ostrich/science Provider.  But if user set the provider in bk_server.conf,  run bookies it would cause error, becaue current bin package not contains the provider jars:
```
[root@bookkeeper-1 bookkeeper]# vi conf/bk_server.conf 
[root@bookkeeper-1 bookkeeper]# bookkeeper bookie
JMX enabled by default
2017-08-22 01:26:50,525 - INFO  - [main:BookieServer@301] - Using configuration file /opt/bookkeeper/conf/bk_server.conf
2017-08-22 01:26:50,535 - INFO  - [main:BookieServer@410] - Hello, I'm your bookie, listening on port 3181. ZKServers are on test_zookeeper:2181. Journals are in [/data/bookkeeper/journal]. Ledgers are stored in /data/bookkeeper/ledgers.
2017-08-22 01:26:50,538 - ERROR - [main:BookieServer@435] - Exception running bookie server : 
org.apache.commons.configuration.ConfigurationException: org.apache.commons.configuration.ConfigurationException: java.lang.ClassNotFoundException: org.apache.bookkeeper.stats.CodahaleMetricsProvider
	at org.apache.bookkeeper.util.ReflectionUtils.getClass(ReflectionUtils.java:102)
	at org.apache.bookkeeper.conf.ServerConfiguration.getStatsProviderClass(ServerConfiguration.java:1972)
	at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:414)
Caused by: org.apache.commons.configuration.ConfigurationException: java.lang.ClassNotFoundException: org.apache.bookkeeper.stats.CodahaleMetricsProvider
	at org.apache.bookkeeper.util.ReflectionUtils.getClass(ReflectionUtils.java:63)
	at org.apache.bookkeeper.util.ReflectionUtils.getClass(ReflectionUtils.java:93)
	... 2 more
Caused by: java.lang.ClassNotFoundException: org.apache.bookkeeper.stats.CodahaleMetricsProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.bookkeeper.util.ReflectionUtils.getClass(ReflectionUtils.java:61)
	... 3 more
```

This issue is to track the supporting to fix this error.

4. Sub task:
- [x] Make Prometheus provider the default in bk_server.conf, 
- [x] Include stats providers in a -all package, #499 
- [x] Change docker image for this supporting work.
- [x] If user use their own stats provider, write a document on how to use it.

**Comment by sijie** [comment]
@zhaijack I think it is a general problem for plugins. we might be facing the same problem for http endpoint. it might be good to raise an email thread to discuss what will be packaging stories for plugins.

**Comment by eolivelli** [comment]
Yes, maybe a new BP. We have to separate the client code from the server side code too.
I think that the assembly plugin should live in a separate project which will be able to depend on all other maven artifacts. This is the practice I am following in my projects, it makes packaging simpler

**Comment by sijie** [comment]
I think separating assembly plugin to a separate module is a good suggestion. +1 to what @eolivelli suggested.

separate client code from server side should be a separate topic. it can be a BP. for this issue, let's try to address real issues first.

**Comment by eolivelli** [comment]
@zhaijack After re-reading the issue, I think that Codehale should be the default and maybe we should enable JMX by default.
Does PrometheusMetricsProvider support publishing data via JMX ? In my experience JMX is most common way to monitor JVMs

**Comment by sijie** [comment]
@eolivelli prometheus has jmx support, I believe. I don't think it really matters what is the default stats provider here. It is more about including a list of stats providers for people to choose.

**Comment by eolivelli** [comment]
@sijie yes I agree you are right

**Comment by sijie** [comment]
Closed this.

- server binary distribution includes prometheus provider by default.
- all binary distribution includes all supported metrics providers.
- docker and documentation are updated.
