### ISSUE TITLE
make pushing a docker image as part of the release procedure

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#585]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-974

Reporter: Jia Zhai @jiazhai

make pushing a docker image as part of the release procedure.

### Comments from JIRA

---
*Francesco Caliumi* 2016-11-23T16:30:15.663+0000

Hi [~zhaijia], I'm interested in creating an automated docker build for bookeeper. I'm experienced with docker builds but not with automated builds / dockerhub and I would like to take the opportunity to deepen my knowledge about it.

Is this the correct issue for this topic or maybe https://issues.apache.org/jira/browse/BOOKKEEPER-972?

Thanks,
Francesco.

---
*Sijie Guo* 2016-11-23T17:20:36.630+0000

Francesco, yes! This is the jira for automating the builds. BOOKKEEPER-972 is the master ticket for traking the whole work.

---
*Francesco Caliumi* 2016-11-24T09:16:57.312+0000

Thanks Sijie, a couple of questions:
- What is the best place to maintain docker builds? A subdir in the bookkeeper official git repo (e.g. docker-builds) or a different project maybe on GitHub (e.g. bookkeeper-docker-builds)?
- As a starting point I think we could use [Zookeeper official docker image|https://hub.docker.com/_/zookeeper/] (looking further I found [this project|https://hub.docker.com/r/michalrmiller/docker-bookkeeper/] that seems to be very close to what I had in mind). This means Alpine with Java OpenJDK 8 like base image and the Bookkeeper release in https://archive.apache.org/dist/bookkeeper/bookkeeper-X.Y.Z/bookkeeper-server-X.Y.Z-bin.tar.gz. Any different indication or suggestion?

Thanks,
Francesco.

---
*Enrico Olivelli* 2016-12-02T20:54:37.434+0000

I have found this very interesting article about the creation of images during the build
https://www.alooma.com/blog/building-dockers

Maybe we can add a maven profile which creates and eventually pushes the image to a repository

[~fpj] During the last community  meeting we talked about having an official bk image on docket hub. How did you achieve it on Zookeeper ? 

---
*Jia Zhai* 2016-12-07T11:05:01.286+0000

Yes, for zookeeper the fist docker image is marked as *"official"* in this list: [https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=zookeeper&starCount=0] 

Hi, Francesco, Glad for you help, and sure,  you could take this issue.
And for bookkeeper, There is a already a docker account user/psw: bookkeeper/bookkeeper, you may use it directly, if you like.

---
*Enrico Olivelli* 2016-12-07T12:33:15.374+0000

IMHO The credentials for this account should not be public and so easy.

[~hustlmsp] [~fpj] what do you think ? is there any secure credentials repository ?

---
*Sijie Guo* 2016-12-07T15:17:30.867+0000

Hmm, I agreed with [~eolivelli]. [~zhaijia] we shouldn't share the credentials publicly.

---
*Sijie Guo* 2016-12-07T15:18:07.962+0000

[~fpj] can you share the experiences on how zookeeper manages the official docker image with the community?

---
*Jia Zhai* 2016-12-08T06:40:28.258+0000

Yes, agree. We could change the password before the first push, if we will use it.

---
*Jia Zhai* 2016-12-08T06:56:17.961+0000

Regarding the "official" tag, for our bookkeeper, we need pull request to docker-github:
    docker-library/official-images [https://github.com/docker-library/official-images]
    docker-library/docs [https://github.com/docker-library/docs]
Then the Official Repositories team, with help from community contributors, formally review each proposal and provide feedback to the author.

Here is a more detailed introduction of it:
[https://docs.docker.com/docker-hub/official_repos/]

---
*Flavio Junqueira* 2016-12-10T15:08:16.032+0000

yeah, we don't. some volunteer did it on his own, so the "official" label is a bit tricky because it isn't official from a community perspective. it would be much better if it were community driven, like this community is trying to do.

---
*Francesco Caliumi* 2016-12-13T23:22:55.317+0000

I've created the repo [https://github.com/caiok/docker-bookkeeper] for the bookkeeper build.

It should be ok, but I didn't test in a fully operating ensemble. I will soon add documentation on how to build the image and how to set up a simple test ensemble (with docker-compose, if possibile).

I'll keep track of progress in this issue.

---
*Enrico Olivelli* 2016-12-14T15:49:36.489+0000

I'm trying your image 
{code}
make build
docker run --network host --name some-zookeeper --restart always -d zookeeper
docker run  --network host -e ZK_SERVERS=$(hostname):2181 -it caiok/bookkeeper:4.4.0
{code}

I get this error:
{code}
2016-12-14 15:43:41,854 - INFO  - [main:ZooKeeper@438] - Initiating client connection, connectString=DNA101PC193.diennea.lan:2181 sessionTimeout=10000 watcher=org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase@6aaa5eb0
2016-12-14 15:43:41,872 - INFO  - [main-SendThread(dna101pc193.diennea.lan:2181):ClientCnxn$SendThread@975] - Opening socket connection to server dna101pc193.diennea.lan/10.168.101.193:2181. Will not attempt to authenticate using SASL (unknown error)
2016-12-14 15:43:41,913 - INFO  - [main-SendThread(dna101pc193.diennea.lan:2181):ClientCnxn$SendThread@852] - Socket connection established to dna101pc193.diennea.lan/10.168.101.193:2181, initiating session
2016-12-14 15:43:41,929 - INFO  - [main-SendThread(dna101pc193.diennea.lan:2181):ClientCnxn$SendThread@1235] - Session establishment complete on server dna101pc193.diennea.lan/10.168.101.193:2181, sessionid = 0x158fdff2b450000, negotiated timeout = 10000
2016-12-14 15:43:41,931 - INFO  - [main-EventThread:ZooKeeperWatcherBase@127] - ZooKeeper client is connected now.
2016-12-14 15:43:41,941 - ERROR - [main:Bookie@434] - BookKeeper metadata doesn't exist in zookeeper. Has the cluster been initialized? Try running bin/bookkeeper shell metaformat
2016-12-14 15:43:41,945 - ERROR - [main:Bookie@391] - Couldn't access cookie in zookeeper
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for BookKeeper metadata
	at org.apache.bookkeeper.bookie.Bookie.getInstanceId(Bookie.java:437)
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:346)
	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:494)
	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:110)
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:96)
	at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:386)
2016-12-14 15:43:41,947 - ERROR - [main:BookieServer@403] - Exception running bookie server : 
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for BookKeeper metadata
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:392)
	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:494)
	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:110)
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:96)
	at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:386)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for BookKeeper metadata
	at org.apache.bookkeeper.bookie.Bookie.getInstanceId(Bookie.java:437)
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:346)
	... 4 more

{code}

Some ideas:
- maybe we should mount separate volumes for data/index/journal by default
- maybe we should have a way to pass the configuration file or single configuration options
- maybe we should have a way to run the bookkeeper shell

---
*Francesco Caliumi* 2016-12-17T15:27:07.828+0000

Hi [~eolivelli], thanks for trying it out.
Yes, bookies need that ZK metadata is properly formatted in order to start and as a workaround you can pass "--env FORMAT_METADATA=yes" when running the first BK container. This is obviously not the ideal solution, though. A better one should be to check ZK if metadata is present and format if it isn't.

About your ideas:
- data/index/journal in separate volumes: absolutely right
- configuration file: there are different ways of achieving this, but they are not straight forward. About configuration, I could create a volume (e.g. /conf) that, if it contains something, it will replace the bookkeeper/conf dir. Then what we should do with env variables (like ZK_SERVERS)? In my opinion it would be better to not substitute them in conf file because if the user doesn't specify anything they will be replaced by default ones. However, if the user specify a variable, it won't be replaced if /conf is present, that bring to a counterintuitive behavior (IMHO). What's your opinion?
- single configuration options: yes, I will add a env variable "BOOKIE_OPTS" that will be appended to bookie command at run (i.e. bin/bookkeeper bookie ${BOOKIE_OPTS})
- bookkeeper shell: sure. I was thinking to pass any parameters given to docker run directly at bin/bookkeeper, like:
{code}
docker run --rm --network host -e ZK_SERVERS=$(hostname):2181 -it caiok/bookkeeper:4.4.0 shell metaformat
{code}

---
*Enrico Olivelli* 2016-12-22T15:46:24.991+0000

[~hustlmsp] can you assign this issue to  [~Caio] ?

---
*Francesco Caliumi* 2016-12-30T23:25:16.733+0000

I have a problem: docker containers are ephemeral while volume data persists with the device of your choice. Every docker execution is a different container (a container should be merely a process, in the docker way of thinking) that run on same data.

When you stop the fist container that generated data and run another one on this data, this check fails:
{code}
2016-12-30 23:06:35,789 - ERROR - [main:BookieServer@403] - Exception running bookie server : 
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: Cookie [4
bookieHost: "8b5c5ea2b4ea:3181"
journalDir: "/data/journal"
ledgerDirs: "1\t/data/ledger"
instanceId: "23eaa442-8c05-4831-9ca5-b6b02435b8d5"
] is not matching with [4
bookieHost: "cc758a778766:3181"
journalDir: "/data/journal"
ledgerDirs: "1\t/data/ledger"
instanceId: "8e13e0dc-356c-4d02-8d72-a737ac61e85c"
]
	at org.apache.bookkeeper.bookie.Cookie.verify(Cookie.java:97)
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:363)
	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:494)
	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:110)
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:96)
	at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:386)
{code} 

My question: is there a way to disable it or fix the situation in the following runs?

---
*Francesco Caliumi* 2017-01-16T06:18:04.474+0000

The cookie issue was resolved by using a static hostname for docker container and I arrived at a fully working docker image ([https://github.com/caiok/docker-bookkeeper])

I'm now rewriting the docker build in order to adhere to the strict official docker images guidelines. I need a key fingerprint from e.g. [http://ha.pool.sks-keyservers.net/] in order to verify the dist *.asc key, to be used in:
{code}
wget -q "https://archive.apache.org/dist/bookkeeper/bookkeeper-${BK_VERSION}/${DISTRO_NAME}.tar.gz" 
wget -q "https://archive.apache.org/dist/bookkeeper/bookkeeper-${BK_VERSION}/${DISTRO_NAME}.tar.gz.asc" 
export GNUPGHOME="$(mktemp -d)" 
gpg --keyserver ha.pool.sks-keyservers.net --recv-key "<<<KEY>>>" 
gpg --batch --verify "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz" 
{code}

(e.g. zookeeper key fingerprint: 97FC712E4C024BBEA48A61ED3A5CA953F73C700D)

[~hustlmsp] Can you help me?

Thanks,
Francesco.

---
*Jia Zhai* 2017-05-31T00:52:07.139+0000

Hi [~Caio], FYI. Some of the use case is running bookkeeper docker image on DCOS or K8S, And normally, bookkeeper should be a stateful service, which at least need the data of bookies be kept. 
In DCOS or K8S, there is feature "Persistent Volume" provided to achieve stateful, normally, if one bookie got down, DCOS/K8S will *automatically* start a new bookie docker instance, and try it best to run it on the same node, and mounted it with the "persistent volume" that it used at last run.

---
*ASF GitHub Bot* 2017-06-21T09:51:51.944+0000

GitHub user caiok opened a pull request:

    https://github.com/apache/bookkeeper/pull/197

    BOOKKEEPER-974: Add an official bookkeeper docker image

    Docker directory now contains two sub dirs, "4.4.0" that will contain the centos docker build and "4.4.0-alpine" that contains the alpine build. 

You can merge this pull request into a Git repository by running:

    $ git pull https://github.com/caiok/bookkeeper BOOKKEEPER-974

Alternatively you can review and apply these changes as the patch at:

    https://github.com/apache/bookkeeper/pull/197.patch

To close this pull request, make a commit to your master/trunk branch
with (at least) the following in the commit message:

    This closes #197
    
----
commit 04a05d7ffa8de50928bf3814a6312df90a3eb8bb
Author: Francesco Caliumi - Diennea <francesco.caliumi@diennea.com>
Date:   2017-06-21T09:48:55Z

    BOOKKEEPER-974: Add an official bookkeeper docker image

----

---
*ASF GitHub Bot* 2017-06-21T12:51:25.489+0000

Github user jiazhai commented on the issue:

    https://github.com/apache/bookkeeper/pull/197
  
    There seems be an empty file: "docker/4.4.0/.keep", what is the reason to have it?

---
*ASF GitHub Bot* 2017-06-28T21:41:14.316+0000

Github user sijie commented on the issue:

    https://github.com/apache/bookkeeper/pull/197
  
    @caiok any updates on this pull request?

**Comment by ivankelly** [comment]
Already part of the Release guide.
