### ISSUE TITLE
Update Dockerfile in 4.5.1  to use org.apache.bookkeeper.stats.NullStatsProvider

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#780]
In issue #732, we changed Makefile for Docker:
```
BK_statsProviderClass=org.apache.bookkeeper.stats.NullStatsProvider
```
to avoid error:
```
2017-11-28 00:49:50,794 - ERROR - [main:BookieServer@435] - Exception running bookie server : 
org.apache.commons.configuration.ConfigurationException: org.apache.commons.configuration.ConfigurationException: java.lang.ClassNotFoundException: org.apache.bookkeeper.stats.PrometheusMetricsProvider
	at org.apache.bookkeeper.util.ReflectionUtils.getClass(ReflectionUtils.java:102)
	at org.apache.bookkeeper.conf.ServerConfiguration.getStatsProviderClass(ServerConfiguration.java:1971)
	at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:414)
Caused by: org.apache.commons.configuration.ConfigurationException: java.lang.ClassNotFoundException: org.apache.bookkeeper.stats.PrometheusMetricsProvider
	at org.apache.bookkeeper.util.ReflectionUtils.getClass(ReflectionUtils.java:63)
	at org.apache.bookkeeper.util.ReflectionUtils.getClass(ReflectionUtils.java:93)
	... 2 more
Caused by: java.lang.ClassNotFoundException: org.apache.bookkeeper.stats.PrometheusMetricsProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.bookkeeper.util.ReflectionUtils.getClass(ReflectionUtils.java:61)
	... 3 more
```
It is more safe to change the default env in Dockerfile instead of Makefile. So that user use the default 4.5.1 Docker will not meet error.

**Comment by sijie** [comment]
#781 is merged.

**Comment by sijie** [comment]
I cherry-pick the docker file changes and retag 4.5.1. so 4.5.1 docker image should include this change.

btw, I notice 4.5.1 docker image was using 4.5.0 package. @eolivelli just wonder have you updated the docker and do the tag?

**Comment by eolivelli** [comment]
@sijie I think I did the new tag. We checked together. But maybe the builder took anither version, maybe it was kind of cache and re-tagging is not supported.
I really do not know how it works.

Anyway I could be wrong and I did not well, in that case I apologize.
We can check  the commit notifications emails, unfortunately there is not history for tags

**Comment by sijie** [comment]
@eolivelli no worries. the 4.5.1 tag should be right now.
