### ISSUE TITLE
Bookie and BookKeeperAdmin and BookKeeper client does not use shaded Protobuf JAR

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#922]
**BUG REPORT**

1. Please describe the issue you observed:

Bookie depends on non-shaded Google Protobuf 3.4.0

- What did you do?
Start a Bookie (embedded) without Protobuf on the classpath

- What did you expect to see?
The Bookie should start, because we are shading and relocating Protobuf

- What did you see instead?

This is the error on BookKeeper client:
```
java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at magnews.server.ServiceClassLoader.findClass(ServiceClassLoader.java:105)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.bookkeeper.client.LedgerMetadata.parseConfig(LedgerMetadata.java:459)
        at org.apache.bookkeeper.meta.AbstractZkLedgerManager$3.processResult(AbstractZkLedgerManager.java:389)
```

This is the error on BookKeeperAdmin:
```

Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistry
	at org.apache.bookkeeper.proto.BookieClient.<init>(BookieClient.java:108)
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:492)
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:365)
	at org.apache.bookkeeper.client.BookKeeperAdmin.format(BookKeeperAdmin.java:1181)
```

This is the error on Bookie:

```
2017-12-27-11-22-11.938 Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
2017-12-27-11-22-11.938 	at java.lang.ClassLoader.defineClass1(Native Method)
2017-12-27-11-22-11.938 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
2017-12-27-11-22-11.939 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2017-12-27-11-22-11.939 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
2017-12-27-11-22-11.939 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2017-12-27-11-22-11.940 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
2017-12-27-11-22-11.940 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
2017-12-27-11-22-11.940 	at java.security.AccessController.doPrivileged(Native Method)
2017-12-27-11-22-11.941 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
2017-12-27-11-22-11.941 	at magnews.server.ServiceClassLoader.findClass(ServiceClassLoader.java:105)
2017-12-27-11-22-11.942 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2017-12-27-11-22-11.942 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2017-12-27-11-22-11.942 	at org.apache.bookkeeper.bookie.Cookie.parse(Cookie.java:199)
2017-12-27-11-22-11.943 	at org.apache.bookkeeper.bookie.Cookie.readFromRegistrationManager(Cookie.java:336)
2017-12-27-11-22-11.943 	at org.apache.bookkeeper.bookie.Bookie.readAndVerifyCookieFromRegistrationManager(Bookie.java:363)
2017-12-27-11-22-11.944 	at org.apache.bookkeeper.bookie.Bookie.checkEnvironmentWithStorageExpansion(Bookie.java:442)
2017-12-27-11-22-11.944 	at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:282)
2017-12-27-11-22-11.944 	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:642)
2017-12-27-11-22-11.945 	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:102)
2017-12-27-11-22-11.945 	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:83)
```

**Comment by eolivelli** [comment]
@sijie  if I switch to bookkeeper-server with 'shaded' classifier now I get this new error,
I think it is because we are not processing the bookkeeper-common module with the shade plugin

```
java.lang.NoSuchMethodError: org.apache.bookkeeper.util.OrderedSafeExecutor.chooseThread(Ljava/lang/Object;)Lbk-shade/com/google/common/util/concurrent/ListeningScheduledExecutorService;
	at org.apache.bookkeeper.proto.BookieRequestProcessor.processReadRequestV3(BookieRequestProcessor.java:318)
	at org.apache.bookkeeper.proto.BookieRequestProcessor.processRequest(BookieRequestProcessor.java:213)
	at org.apache.bookkeeper.proto.BookieRequestHandler.channelRead(BookieRequestHandler.java:81)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.apache.bookkeeper.proto.AuthHandler$ServerSideHandler.channelRead(AuthHandler.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:979)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:401)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by eolivelli** [comment]
@sijie the bookkeeper-server with 'shaded' classifier has the protobuf dependency

just try:
```
<dependency>
            <groupId>org.apache.bookkeeper</groupId>
            <artifactId>bookkeeper-server</artifactId>
            <version>4.5.1</version>
</dependency>
```
and run 
`mvn dependency:tree`

you won't see protobuf

```
+- org.apache.bookkeeper:bookkeeper-server:jar:4.5.1:compile
|  +- org.slf4j:slf4j-log4j12:jar:1.7.25:compile
|  +- org.apache.commons:commons-lang3:jar:3.3.2:compile
|  +- net.java.dev.jna:jna:jar:3.2.7:compile
|  +- io.netty:netty-all:jar:4.1.12.Final:compile
|  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.3.Final:compile
```

if you switch to 4.6.0 version
```
<dependency>
            <groupId>org.apache.bookkeeper</groupId>
            <artifactId>bookkeeper-server</artifactId>
            <version>4.5.1</version>
            <classifier>shaded<classifier>
</dependency>
```

you will see the protobuf 3.4.0 dep
```
+- org.apache.bookkeeper:bookkeeper-server:jar:shaded:4.6.0:compile
|  +- org.apache.bookkeeper:bookkeeper-common:jar:4.6.0:compile
|  +- com.google.protobuf:protobuf-java:jar:3.4.0:compile
|  +- org.slf4j:slf4j-log4j12:jar:1.7.25:compile
|  +- org.apache.commons:commons-lang3:jar:3.3.2:compile
|  +- org.apache.commons:commons-collections4:jar:4.1:compile
|  +- net.java.dev.jna:jna:jar:3.2.7:compile
|  +- io.netty:netty-all:jar:4.1.12.Final:compile
|  +- io.netty:netty-tcnative-boringssl-static:jar:2.0.3.Final:compile
|  \- org.apache.bookkeeper.http:http-server:jar:4.6.0:compile
|     +- com.fasterxml.jackson.core:jackson-core:jar:2.8.9:compile
|     +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.9:compile
|     \- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.9:compile
```

**Comment by sijie** [comment]
okay I see. bookkeeper-common is not included in the shaded plugin. we need to make sure we include bookkeeper-common in the shaded plugin.
