### ISSUE TITLE
Bookie server failed to start when running daemonset in GKE

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#960]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

Running a 10-nodes bookkeeper cluster in GKE using daemonset.

- What did you expect to see?

The bookkeeper cluster can run long time without any problems

- What did you see instead?

A bookie pod got into a crashloop and can't come back online anymore.

```
2018-01-08 17:18:43,186 - ERROR - [main:Bookie@369] - Couldn't access cookie in zookeeper
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /ledgers/cookies/10.128.0.12:3181
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
    at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
    at org.apache.bookkeeper.bookie.Cookie.writeToZooKeeper(Cookie.java:214)
    at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:366)
    at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:481)
    at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:313)
    at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:116)
    at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:589)
2018-01-08 17:18:43,187 - ERROR - [main:BookieServer@606] - Exception running bookie server : 
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /ledgers/cookies/10.128.0.12:3181
    at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:370)
    at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:481)
    at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:313)
    at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:116)
    at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:589)
Caused by: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /ledgers/cookies/10.128.0.12:3181
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
    at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
    at org.apache.bookkeeper.bookie.Cookie.writeToZooKeeper(Cookie.java:214)
    at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:366)
    ... 4 more
```

**Comment by sijie** [comment]
The problem of running bookies using daemonset is from the physical machines are vms. These vms are using ephemeral storage (local ssds) as the storage. so when a physical machine is gone, the disks are gone. However the vm would still come up with same ip address, with new local disks, a new bookkeeper pod will attempt to use the same ip address to advertise and fail, because local disks are gone.

**Comment by sijie** [comment]
It is a bit tricky to get around with daemonset in cloud environment. It is recommended to run bookkeeper using statefulset in cloud environments.

**Comment by maurya-m** [comment]
@sijie , as suggesting here have tried setting up using statefulset using DNS records for the zk servers, but still the bookie servers are crashlooping , any pointers , have open a question , can please help here , thanks  for the support. https://github.com/apache/bookkeeper/issues/2080

**Comment by shoothzj** [comment]
I think we are recommending running bookkeeper with persistent disk storage. Won't fix this.
